### ISSUE TITLE
[Stress Testing Possible Bug] Iridium may be the source of my constant crashing in Vivaldi

### ISSUE THREAD

**Issue by NovaViper** [ParticleCore/Iridium#111]
Hi, I'm reporting something rather strange going on with Vivaldi. I'm adding this issue because I think that this extension as a user script is causing problems with Vivaldi, which leads to it crashing. I'm using Vivaldi 
1.11.917.43 and Iridium 0.1.7b with Tampermonkey. And yes, I do know that Vivaldi isn't officially supported as of now until Iridium's full release, but I just wanted to let you know of this possible bug. Right now I'm stress testing the browser to determine what extensions/userscripts are causing it to crash. I will post an update of the issue when I can determine the source of the crashing.

If I happen to find that the script isn't the issue, then I'll close the issue. If the script is the issue, then I'll update the issue.

Sorry for the inconvenience

**Comment by ParticleCore** [comment]
Be aware that Tampermonkey can be causing the problem since it works at a way higher level than the userscript it injects. Also, Iridium has recently switched from remote loading the CSS to letting Tampermonkey loading it by itself @ https://github.com/ParticleCore/Iridium/blob/a22871c739e9ef947655bbefc1f0d9d6b8b3d4e2/src/userscript/Iridium.user.js#L8

which appears to cause the userscript to run later than it should when it tries to load the CSS for the first time(s) (typically during first installation or version update).

**Comment by NovaViper** [comment]
Oh? Then should I switch to a different script engine? Or change something within Tampermonkey?

**Comment by ParticleCore** [comment]
I honestly do not know, I just thought you should know to take it into account during your tests. Anything else is outside the support of this issue tracker.

**Comment by NovaViper** [comment]
Ah ok.. I might test out a different userscript engine, just to see how it affects the performance. There is actually a noticeable performance drop when going on YT with Tampermonkey enabled. I discovered this as I was stress testing the browser

**Comment by NovaViper** [comment]
Huh, Tampermonkey may have had a part in the crashing after all. Youtube loads MUCH faster than before with ViolentMonkey

**Comment by NovaViper** [comment]
I'm going to close this issue, if I spot something else I'll open it back up and update it
