### ISSUE TITLE
Keep Dark Mode in sync with youtube's setting

### ISSUE THREAD

**Issue by MattSturgeon** [ParticleCore/Iridium#130]
Follow up to  #128, it would be nice if the dark mode setting in Iridium also affected (and was affected by) the dark mode setting in the youtube menu.

This would require keeping track of the cookies/local storage where youtube store their settings and paging for changes. Alternatively youtube may fire an event that could be listened to.

_As always, no expectation of this being added, simply filing the feature request for the record_

**Comment by jcdenton2k** [comment]
I would also like this Iridium 'dark theme' toggle to also affect YouTube.  It can be separate (Iridium Dark Theme UI and YouTube Dark UI) or it can be integrated into one toggle.
YouTube already has a 'Dark Theme' setting but it has to be set manually when visiting youtube every time.  If something can be done to 'remember' this setting across browser sessions without needing to use (third-party) cookies then this would work quite well.

**Comment by ParticleCore** [comment]
This has been implemented in version 1.0.0, however listening to the cookie changes proved to be to heavy in processing since YouTube is constantly updating them which means if the user has multiple windows opened the even is triggered multiple times which stacks up pretty fast. The only solution was to enforce it on the extension side and the settings page of the extension follows YouTube's current theme as well.
