### ISSUE TITLE
Disabled autoplay is buggy with timestamps

### ISSUE THREAD

**Issue by Keith94** [ParticleCore/Iridium#14]
If you have 'Play videos automatically' disabled, clicking on a timestamp for a video doesn't seek/resume the video automatically like it should.

For example, this comment
https://www.youtube.com/watch?v=BlBSRft7RME&lc=z13nwhsiapvrc5awl04ccdljnufocniyiss0k

**Comment by ParticleCore** [comment]
This is not related to the extension, it is the YouTube Material layout that has the timestamps broken. I noticed that earlier when I was trying to jump to certain timestamps while watching long music compilation links.

You can confirm this by turning the extension off and clicking on the timestamp, it will redirect you to the same page with the timestamp added on the url, instead of just staying on that page and seek the video to the respective clicked time.

Also the autoplay setting will persist for ampersand timestamps links, such as "&t=12s", by design. It will, however, let the video play automatically if it uses the proper hashtag timestamps used for seeking inside the video pages, such as "#t=12s", which is often used by YouTube itself inside comments and video descriptions. In fact, had that comment link been working correctly, clicking on it would make YouTube load the time internally using the hashtag timestamp, allowing you to seek directly to that time, playing it automatically and without forcing you to reload the page. You can see this clearly with YT+ if you switch back to the classic layout and test the same situation.

Seeing that this is a YouTube bug it would be advised that you report it to the YouTube team via the "Send feedback" link on the top right menu.

**Comment by Keith94** [comment]
My apologies, I assumed it was a problem with the script. I'll report it if it doesn't get fixed officially soon.
