### ISSUE TITLE
[CSS] #iri-quick-controls placement

### ISSUE THREAD

**Issue by RaitaroH** [ParticleCore/Iridium#143]
EDIT: I understand. Well, maybe in the future.
I recommend putting the controls above the like/dislike buttons to use the empty space.

```
#iri-quick-controls {
    font-size: 0;
    margin-bottom: 45px;
    margin-top: -85px;
    position: relative;
    text-align: right;
}
```

Like so:
![screenshot from 2017-09-06 10 52 58](https://user-images.githubusercontent.com/19552720/30100440-955d7688-92f1-11e7-978f-a8ae746680b8.png)

**Comment by tympapost** [comment]
I would also like that placement, mainly because when I use the theater mode, quick controls are below the visible screen space and I need to scroll the page to use them. But... this may not be always the best place to put them:
![ss](https://user-images.githubusercontent.com/6545650/30101190-09502ade-92f4-11e7-8865-74ec9ce4942a.jpg)

**Comment by ParticleCore** [comment]
The option was studied and the conclusion was that it would cause the titles to not update when changing videos because the controls were placed on that area. Other options were investigated, but this one was the best so far, given all the downsides found. This does not mean they cannot be changed, but for now they will stay where they are.

**Comment by ParticleCore** [comment]
Opening this since the current placement is not the best for laptops with 1366x768 resolution.

**Comment by tympapost** [comment]
I've seen other modifications that add controls to the control bar, so I know that it is possible. Difficult to maintain perhaps, but possible.
![clipboard image](https://user-images.githubusercontent.com/6545650/31497611-4a69e8c6-af68-11e7-8701-33f3312c13f4.jpg)

**Comment by RaitaroH** [comment]
Hmm... I did manage to get something more usable, but I had to theme youtube itself and iridium to get it working right. I do have a 1366x768 px laptop btw.
120% zoom:
![screenshot from 2017-10-13 15 16 54](https://user-images.githubusercontent.com/19552720/31545825-90da8eca-b029-11e7-9df7-c3de7866d111.png)
100% zoom:
![screenshot from 2017-10-13 15 17 25](https://user-images.githubusercontent.com/19552720/31545856-ab355e26-b029-11e7-86e8-fd42e739682f.png)


CSS changes:
```
#top.ytd-watch
{
	margin-top: 0px !important;
}
#page-manager.ytd-app
{
	margin-top: 45px !important; /*for 130% do 50px*/ 
}
#container.ytd-masthead
{
	height: 40px !important;
}
#iri-quick-controls
{
	margin-bottom: -22px !important;
}
```

**Comment by ParticleCore** [comment]
Ideally I want to avoid having to mess with native YouTube layout as much as possible, I am trying to achieve the first suggested idea or inline with the like/dislike et al action buttons.

**Comment by webfischi** [comment]
![can t see anything](https://user-images.githubusercontent.com/22318963/31965965-5ccd2596-b909-11e7-90f0-028780372761.png)

My native resolution is 1920x1080 and I don't see any controls without scrolling, and there is a huge gap between title and video, so it shouldn't be a big problem to put them on the left side video and video title.
