### ISSUE TITLE
Intent to add opt-in telemetry

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Iridium#149]
This is a preliminary discussion on the intent to add an option for users to choose whether or not they wish to enable telemetry, turned off by default. This decision is not final because I never liked the idea behind sending usage data to a service that I don't control nor the idea of sending data all together.

The objective behind this is mainly to open new opportunities for business (selling data/statistics) and have a much better insight on the usage of the extension. This will help make me understand what is the app mainly used for and see which features are not worth keeping any longer, as well as see flaws that can be improved. The business aspect of it speaks for itself, it's a venue that I would like to explore for profit, however donations have been surging a lot more recently and because of that the business aspect might actually never go forward.

I would like to hear some input from the user base on this, especially if anyone has any service suggestions for this purpose as well as other related suggestions / opinions. Currently I only found Google Analytics to work well during the tests I made on my own, but I would really prefer not to use it.

The main goal of the service I am looking for is one that fits most of the following list, which is not set in stone:

- [ ] Open source (this one is optional, but preferred)
- [ ] Free ("up to" limitations are ok)
- [ ] Easy UI / Graphical visualization
- [ ] Access to collected data / raw data
- [ ] Does not require remote code / dedicated scripts
- [ ] Has to respect DNT (Do Not Track) choice

**Comment by tympapost** [comment]
As long as Iridium remains open source, I have no problem with telemetry, and from a professional standpoint I can understand your intentions. 
Too bad I don't have any suggestions for providers. I have used G.Analytics in the past and I can say it works quite well and it's easy to work with with nice tools and eye candy.

**Comment by bkimmett** [comment]
You might try talking with the Ghostery / Human Web people: they're doing something similar through the current iteration of the Ghostery app (opt-in only). I don't know if they want any other data sources other than those gathered by Ghostery itself, though.

**Comment by losuler** [comment]
The only two free and open source alternatives to Google Analytics I'm aware of are [Piwik](https://piwik.org/) and [Open Web Analytics](http://www.openwebanalytics.com/). It seems Piwik is substantially more active and has greater support, and upon brief assessment, appears to fulfill most of your requirements. Derived from the list you outlined:

## Piwik
- [x] [Free and open source software](https://piwik.org/free-software/)
- [x] Core and [most of it's features](https://piwik.org/features/) are [monetarily free](https://piwik.org/faq/new-to-piwik/#faq_145)
_There are some additional [paid premium features](https://plugins.piwik.org/premium)_
- [x] [Easy UI/graphical visualization](https://piwik.org/docs/piwik-tour/#piwik-overview)
- [x] [Access to collected data/raw data](https://piwik.org/faq/how-to/faq_24574/)
- [ ] Does not require remote code/dedicated scripts
_This is the only point is doesn't fill and I don't think it's surprising since they don't have the resources or additional business avenues that Google benefits from. But I consider this a moot point given how [insanely cheap a VPS is](https://www.reddit.com/r/selfhosted/comments/5c93f1/any_cheap_vps_services/), with many different providers offering instances with more than enough resources for as little as $3. There's also [Amazon's AWS free tier](https://aws.amazon.com/free/) for 12 months and is comparatively cheap there onwards._
- [x] [Respects DNT (Do Not Track) by default](https://piwik.org/docs/privacy/#step-4-respect-donottrack-preference)

I personally think it's a small price to pay for the greater control of the privacy of the data over that of Google Analytics. GA being free in part for how it's lacks in this. However if for any reason the other offerings do not fulfill that of which GA does for you, I think an opt-in is a reasonable compromise. 

In any case, I think the most important thing for users is transparency in which ever direction you take this, that all users be sufficiently notified and informed. So I appreciate you opened this for discussion.

**Comment by ParticleCore** [comment]
@losuler That sounds like the best option/combo so far, aside from the VPS expenses and having to dedicate time to set it up, which is something I do not have to spare for now. Regardless, it will be under great consideration, but for now the focus is mostly on a free, ready to roll online alternative GA. Thank you for the very detailed suggestion, I greatly appreciated reading it.

**Comment by ParticleCore** [comment]
This idea will be placed on the side for now, at least until after #189 is finished.

So far the only service that fits the profile I am looking for is Google Analytics and will probably be the one chosen, but until that decision is made this discussion will be reopened.
