### ISSUE TITLE
Add Chrome compatible tag to userscript version

### ISSUE THREAD

**Issue by gofirst2220** [ParticleCore/Iridium#15]
I tested the userscript in Chrome and it worked really well, so why not mark it as compatible with Chrome?
I know that you are dropping the Chrome Store extension in favor for Opera Store's version, but I'm using the userscript at the moment.

**Comment by ParticleCore** [comment]
Just because it works does not mean it will keep working. It might also work well with all the multiple Chrome forks, but that does not justify marking it as compatible. I provide support to the browsers that I use, adding more is not something I want to do especially when I have very limited time for this.

But Chrome might become one, if the Webstore remains stable for the next weeks.
