### ISSUE TITLE
Changing volume with mousewheel works differently than with Youtube+

### ISSUE THREAD

**Issue by ganego** [ParticleCore/Iridium#157]
Video in theater mode. Volume change with mousewheel enabled.

With YT+ you could hover the mouse left or right of the actual video and the mousewheel could be used to scroll the website. If you clicked left or right of the video it also did not pause the video but then focus, so you can scroll down.
With Iridium scrolling left or right of the video will change volume, clicking will un/pause the video.

**Comment by Eisys** [comment]
This is because with the new Material design, the player stretches across the entire page.
So even though the actual video itself is in the center, the whole player is pagewide and hovering over the player enables volume scrolling and un/pausing the video.

This is not a bug with Iridium.

**Comment by ParticleCore** [comment]
Just like @Eisys explained, this is working exactly as expected since the new layout stretches the entire player to fill the browser width during theater mode, meaning that the "black sides" are actually still part of the player itself, thus the volume will be controlled via the mouse if that option is enabled.

**Comment by ganego** [comment]
But you could just attach the 'wheel' event listener to some other element like the video tag?

**Comment by ganego** [comment]
Oh I just had a look at your code, it's even easier than that since you do some checks anyway.

Just change 
`if (can_scroll && player && api && api.contains(event.target)) {`

to
`if (can_scroll && player && api && player.contains(event.target)) {`

**Comment by ParticleCore** [comment]
Not an option since there are vertical videos which cause the video element to not occupy the width of the player as well as horizontal videos that don't occupy the height of the player, meaning that when you are watching those videos and try to scroll on those "black areas" the volume will not change.

You can make that change on your end if you want, but the feature will remain unchanged on the original repository. Just keep in mind that changing the code usually causes the auto-update to turn off.

**Comment by ganego** [comment]
> Not an option since there are vertical videos which cause the video element to not occupy the width of the player as well as horizontal videos that don't occupy the height of the player, meaning that when you are watching those videos and try to scroll on those "black areas" the volume will not change.

> meaning that when you are watching those videos and try to scroll on those "black areas" the volume will not change.

Yes, and this is exactly how it behaved all the time in YT+. 
This is why the new behavior is inferior, it will change the volume everywhere in the black area, whereas with YT+ it only worked on the <video> tag - which makes a lot more sense to change the volume of the video while hovering over the video and not while hovering over some black area that has nothing to do with the video. I don't see why you want to change that feature from how it worked in YT+. It's a lot harder to scroll to the comments when basically most areas of the screen capture the 'wheel' event and bend it to volume control.

Besides that the new script is quite nice, thank you for working on it after YouTube changed their layout.

**Comment by ParticleCore** [comment]
The feature never changed, it's the YouTube player that changed with the new update, now the player fills the entire browser width when in theater mode whereas the previous layout did not and the available "solutions" are not solutions given the examples I provided, which is a problem since you never know if the black areas do belong to the original video or are included by the player itself until you try to change volume/scroll over them. Changing volume depending on the video element is not a solution for this and for this reason it will remain as it is.

You can submit your feedback to YouTube to let them know that you prefer the previous theater mode over the current one.
