### ISSUE TITLE
Youtube movies fail to load if Iridium is enabled

### ISSUE THREAD

**Issue by Jyrka98** [ParticleCore/Iridium#169]
Browser Name: Chrome

  Browser Version: 61.0.3163.91

  Operating System: Windows 10

  Software Type: Userscript

  Software Version: 0.2.7b

  Userscript Manager: Tampermonkey

  Userscript Version: 4.3.6

  Problem Description: Youtube Movies fail to load if Iridum is enabled.

  Steps to reproduce: 
 - Enable Iridium
 - Watch a purchased movie

  Additional details: 
 Image of video(loading circle behing the play button): https://i.imgur.com/FqsDaxQ.png
 Only full (purchased) movies seem to be affected. Previews work as they should.

**Comment by ParticleCore** [comment]
I am sorry, but I don't have a way to test this on my end to see if there is a fix for it. Is there anything showing on the console when that problem occurs?

**Comment by Jyrka98** [comment]
This is the only thing that may be relevant:

```
base.js:2719 It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior, potentially including failure to play.
LM @ base.js:2719
g.h.Pv @ base.js:6535
AV @ base.js:3389
$qa @ base.js:4164
A1 @ base.js:4145
(anonymous) @ base.js:7268
(anonymous) @ VM1258:1878
ytplayer.load @ watch?v=f7LvM8G3kGs:155
(anonymous) @ watch?v=f7LvM8G3kGs:155
(anonymous) @ watch?v=f7LvM8G3kGs:155
```

**Comment by ParticleCore** [comment]
Don't know if we will be able to tackle the problem like this, but if you are up for it we can try.

Let's move to a Gist so that other subscribers of this repository don't receive email spam for the following test battery we will conduct, head here where we can comment freely at the bottom of the gist: https://gist.github.com/ParticleCore/f338723626da95be652c758ecf35b66f

**Comment by RadioActiveLobster** [comment]
I can confirm this does not appear to be an issue (tested with a purchased version of Guardian's of the Galaxy Vol 2, The Force Awakens and Doctor Strange) on the FireFox version. It might be Chrome specific.

  Browser Name: **FireFox**

  Browser Version: **55.0.3 (64-bit)**

  Operating System: **Windows 10 Pro 64-bit**

  Software Type: **Userscript**

  Software Version: **0.2.8b**

  Userscript Manager: (Remove this line if you are not using the userscript version) **Tampermonkey**

  Userscript Version: (Remove this line if you are not using the userscript version) **v4.4.5484**

**Comment by ParticleCore** [comment]
It might also be a case of some settings he has enabled/disabled, but you don't. It is always a hard time trying to find out these things in these situations.

**Comment by RadioActiveLobster** [comment]
Well, for the sake of testing here are my settings with it confirmed working.

[General](https://i.imgur.com/Hy8LuBE.png)
[Video](https://i.imgur.com/a0JzXuq.png)
[Settings](https://i.imgur.com/3ilDmZM.png)

**Comment by Jyrka98** [comment]
The movie plays fine when using the script from the gist.

**Comment by ParticleCore** [comment]
Looks like gist notifications are broken for over 4 years: https://github.com/isaacs/github/issues/21
We'll have to notify each other here, because three it simply isn't possible.

Edit that script on your end and uncomment this line

````js

if (user_settings.player_quality !== "auto" && (player = document.getElementById("movie_player"))) {

    // player.setPlaybackQuality(user_settings.player_quality); <-- remove the two slashes

}
````

Try again to see if the movie keeps playing fine.

**Comment by ParticleCore** [comment]
Also, do you have any settings that are different than @RadioActiveLobster ? Might move this faster if we know that at a glance.

**Comment by Jyrka98** [comment]
With that line uncommented the video doesn't play. Worked again as soon as i commented it again.

https://i.imgur.com/49n1G9P.png
https://i.imgur.com/EG9LSTa.png

**Comment by ParticleCore** [comment]
That's progress. Now the next step is to leave it commented as it was and uncomment this line now, it's right above the previous one:

````js
var player;

// context.modArgs(config.args);

temp = original.apply(this, arguments);
````

**Comment by Jyrka98** [comment]
Still works

**Comment by ParticleCore** [comment]
Then we are closer to the problem, I believe this is because the default quality feature is not checking if the user choice is available for that video, so it sets it any way. Works with normal videos, clearly not with paid movies. Next step is to see if it is the function itself that is the problem or the quality choice.

Check which quality options are available in the movie you want to watch, then uncomment the line that was causing the problem. After that go to the Iridium settings and change the default quality to one that is available on that movie. Try to play it again and see if the problem is gone.

**Comment by Jyrka98** [comment]
It plays when using the highest quality available for the movie (480p), as soon as i go any higher there is a second of high cpu usage and then it shows the loading circle forever.

**Comment by ParticleCore** [comment]
So that's the problem, I have to find a way to check the available quality settings before enforcing the user default, fallback to the closest in case it isn't available. Thanks a lot for your help and patience, I'll try to come up with a fix this weekend and hope to hear your feedback. Sorry for the trouble you went through because of all this and sorry for all subscribers for all the spam, couldn't be avoided.

**Comment by Jyrka98** [comment]
I fixed it myself. Don't know if it's the best way, but it works.
```
if (user_settings.player_quality !== "auto" && (player = document.getElementById("movie_player"))) {
    var availableQualities = player.getAvailableQualityLevels();
    if (availableQualities.includes(user_settings.player_quality)) {
        player.setPlaybackQuality(user_settings.player_quality);
    }
}
```

**Comment by ParticleCore** [comment]
It is almost exactly like what I was planning on doing, but there still needs to be a check for whether the user choice missing is that of a high quality or low quality, this is because users might have the highest quality set because they want the highest possible, but others have the lowest available because they want the lowest possible.

The method you created only does one thing: if the chosen quality exists, set it.

This means that if it does not exist, it will let YouTube decide for itself. My plan is to set the available quality or the closest quality (closest higher if quality was high, closest lower if quality was low).

**Comment by ParticleCore** [comment]
Version 0.3.0b should fix this issue, let me know when you can.

**Comment by Jyrka98** [comment]
It works fine now. Thanks for fixing it!
