### ISSUE TITLE
Feature requests (rant)

### ISSUE THREAD

**Issue by ybnrmalatall** [ParticleCore/Iridium#17]
All you need to focus on is backwards playlist playback, an auto HD function, and a way to disable DASH!
Can you tell me if you plan on getting these things implemented? Otherwise sticking around is useless.

**Comment by ParticleCore** [comment]
Reverse playlist is likely to be implemented, default video quality will be implemented, disable DASH will not and there are many features that are yet not listed, but will be implemented, this is still in alpha stage. I will focus on what I can when I can, I have almost no free time.

If you do not wish to wait then it would be ideal to use some other extension that can offer you what you are looking for.

**Comment by ybnrmalatall** [comment]
I just wanted to know if you plan on working on things that matter. I'll stick around. 
Forgive me on DASH btw, apparently you need firefox for that to work anymore and that can be done with an about:config change and I've now switched to Yandex since it has the fullscreen tabs when you push the cursor to the top. Vivaldi refuses to make me love them. Yandex needs a dark theme bad though.
It gets irritating when you see an updated feature and it turns out to be square images. lol

**Comment by ParticleCore** [comment]
@ybnrmalatall I understand, I have also been feeling the frustration of having to always set the quality whenever I open the browser again, which is why I have added the default quality option on the recent version 0.1.7a
What matters or doesn't is quite different from user to user, which is why I am focusing on what I can, when I can, there is no defined road-map for this. Ideally I would be developing in a close alpha, but seeing that I have almost no free time like I used to when I created YT+, this left me with the only option of doing it publicly and relying on testers' feedback.
