### ISSUE TITLE
Firefox + Tampermonkey no Iridium icon

### ISSUE THREAD

**Issue by BWMerlin** [ParticleCore/Iridium#227]
I switched from Greasmonkey to Tampermonkey in preperation for Firefox 57 as Greasmonkey wasn't updated to support the new version of Firefox.  Iridium appears to work with Tampermonkey in Firefox but the Iridium icon is missing (or I am really blind) from Youtube so I cannot configure any settings.  Using Firefox 56.0.2 64bit with Tampermonkey 4.5.5570 and Iridium 0.3.5b.

**Comment by ParticleCore** [comment]
I just tested the same configuration and the Iridium icon is displaying correctly. Make sure you follow all the troubleshooting steps as requested and not just the ones you think you should follow since this can be a conflict caused either by an add-on you have or something else: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug#troubleshooting

**Comment by BWMerlin** [comment]
Thank you, literally the first step (material layout) fixed this.

**Comment by ParticleCore** [comment]
Glad to hear you got it working!
