### ISSUE TITLE
YouTube overrides Iridium settings for logo link & appearance

### ISSUE THREAD

**Issue by practik** [ParticleCore/Iridium#254]
As noted at https://github.com/ParticleCore/Iridium/issues/253#issuecomment-350131979:

When a new YouTube page is loaded, the "improved" black logo appears for a split second but is then replaced by an animated "YouTube Rewind" logo that links to `https://www.youtube.com/user/theyearinreview` instead of whatever it's set to in the Iridium settings.

This is a trivial issue for me and will presumably go away once December is over, but I wanted to mention it in case the change has implications for other aspects of Iridium.

**Comment by ParticleCore** [comment]
I have yet to receive it on my end, until that happens I cannot fix it.

**Comment by ParticleCore** [comment]
They are using a single image that offsets horizontally each second, which is something I cannot modify in order to change the red color to a neutral theme.

You can see the image here: https://www.gstatic.com/youtube/doodle/yt-doodle-rewind2017-giraffe-1x.png

And higher density version here: https://www.gstatic.com/youtube/doodle/yt-doodle-rewind2017-giraffe-2x.png

As it is this is something that is not worth trying to work around it since it will likely be different with the next doodle, causing this all over again. Will leave it as is for now seeing that it is temporary.
