### ISSUE TITLE
Enhanced thumbnails [feature requests]

### ISSUE THREAD

**Issue by lexx-nightwolf** [ParticleCore/Iridium#261]
Hi.
It will be very nice if you add enhanced thumbnails in your script (like in Youtube Center):
- rating bar and rating count
- thumbnail preview animation (when the mouse is hovering over a video link it will go through every thumbnail available for that specific video)
- video quality
- video duration

Each setting can be options
- visibility: always visible, on mouse hover, on no mouse hover
- position on thumbnail

Thanks:)

**Comment by ParticleCore** [comment]
In the future please read the instructions more carefully: 

> - The one issue per issue applies as well, do not request more than one feature in the same issue

https://github.com/ParticleCore/Iridium/blob/master/CONTRIBUTING.md

**Comment by lexx-nightwolf** [comment]
@ParticleCore I read the rules. so I combined all the settings into one feature - Enhanced thumbnails:)

**Comment by ParticleCore** [comment]
The problem will be in the future for users that are trying to search for one feature and they can't find it requested since it is all bundled up into one request, leading to duplicate requests. This wouldn't be implemented as one feature, but as many, thus the requirement in the rules to make them individually, no matter the user interpretation, otherwise organization is lost.

**Comment by lexx-nightwolf** [comment]
@ParticleCore Oh. it makes sense. excuse me:)

**Comment by Alhaitham** [comment]
+1
