### ISSUE TITLE
Blacklist confirm

### ISSUE THREAD

**Issue by Bersacker** [ParticleCore/Iridium#269]
I'm clicking the Blacklist button unintentionally way to often. 
Then i have to open the settings and find the blacklisted channel that i don't want to blacklist.
I need a confirm to blacklist option or a smaller button or a shift + blacklist button click.

It is way to easy to click the X when you just want to watch another video.

**Comment by ParticleCore** [comment]
I have been studying multiple possibilities since you opened this issue and I can't find a balance between ease of use and ability to "undo" the action easily without investing too much which at that point becomes unjustified.
I will consider adding an option to sort the black list by added date, which I believe it will make this problem easier to revert manually since you will be able to always know which channel you added the last by sorting them in that way.
Unfortunately this will have low priority, so don't expect it very soon.
