### ISSUE TITLE
About video previews

### ISSUE THREAD

**Issue by ddd111ddd** [ParticleCore/Iridium#27]
The video preview (hover) counts as a regular view, triggering analytics, and for many cases that might not be what people want. I would suggest a simple switch between thumbnails like for example:

https://img.youtube.com/vi/NLZRYQMLDW4/1.jpg
https://img.youtube.com/vi/NLZRYQMLDW4/2.jpg
https://img.youtube.com/vi/NLZRYQMLDW4/3.jpg

ps: great work with the new version, I just tried and it's quickly getting into shape!

**Comment by ParticleCore** [comment]
Video previews are exactly what already exist in YouTube Gaming. It is true that it will very likely be registered in the analytics, but I made sure to include the necessary details used on YouTube Gaming previews so that these kind of views can be distinguished from regular views.

Using thumbnails as previews (video storyboards) has never been a sustainable option because they give a terrible experience to users with slow internet connections and there are videos that simply do not have storyboard/thumbnails. For example, these videos and many others do not have them:  

https://www.youtube.com/watch?v=kvARvzMErnk

https://www.youtube.com/watch?v=VCxEjJ1JM1Q

YouTube is aware of this bug, but they have yet to correct it. There are many videos with this problem, so video previews would not work for those videos using that method.

Also YouTube has been testing their own video preview on the main website since 2016 and when, and if it is every released, the removal of this feature might be considered.
