### ISSUE TITLE
Update on the current development status

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Iridium#274]
A new year has come and it was impossible for me to push the stable version. Any free time I hoped to have during this time of year was virtually none, thus absolutely no tangible progress has been made other than stability tests.

The current plan still stands, I still want to finish two major features (reverse playlist - currently almost done - and open player in pop up window), implement automatic locale service and a basic welcome modal with minimal instructions.

Moving forward I definitely will want to implement more features, but only after Iridium is on stable version.

However, I have also been considering dropping the userscript all together after having noticed for the past couple of months that userscript managers are becoming slow at running the userscript, causing crucial initialization steps to miss the timing of the page load, leading to - most noticeably - the player playing when autoplay is off, ads showing when they are disabled, etc. Ideally, to prevent this from happening, the userscript would be converted into a fully fledged extension, but I also do not know whether or not this would be a solution for this problem seeing that browser are focusing more on being faster at load times even if that means sacrificing the loading of any installed extensions, so even this option might not solve this.

Nevertheless, any final decision regarding this will only be made post stable release.

To all I wish you the best and thanks to everyone that helps and even those that only try to help, happy 2018.

**Comment by windowlicker79** [comment]
This is probably the wrong place to ask, but I'm so confused!
I've been using the Youtube+ addon for years. I clicked the link in the blue pop-up to install the new version for the new Youtube layout (called Iridium?)
Where can I download it? I found a link that said "download" but the only thing there is a link that says github and it just opened a page full of code.
Really not sure what to do. I'd like to try it out but where is it??
I'd just stick with the old Youtube+ add-on, but Youtube keeps forgetting that I've chosen to stick with the old layout and keeps switching it back to the new layout (which I can't use as I don't know how to get Iridium!)
Please help!

Running Firefox 57.0.4 on Windows 10.
Used to use the YT+ userscript, but since FF 57 all my userscripts disappeared so I downloaded the add-on. Still got Greasemonkey installed though.

**Comment by ParticleCore** [comment]
@windowlicker79 Current version of Iridium is beta, meaning that is only being developed as a userscript. Add-on / extension version will only be made once it leaves beta stage.

You'll have to use a userscript manager to install Iridium, but due to the recent change in Greasemonkey it is no longer capable of installing userscripts like before, for this reason I would recommend Tampermonkey instead for the time being.

**Comment by windowlicker79** [comment]
Thanls for the quick reply. I'll give Tampermonkey a try.

**Comment by windowlicker79** [comment]
Sorry to bsuch a pain, but now there's another problem!
I've intalled Tampermonkey, went to the Iridium download page, clicked the github link, then clicked the install button. Then the github tab just closed. Nothing is installed. But if I go back to the page the "install" button now says "reinstall". If I click that it does the same thing. Just closes that tab.
Help!

**Comment by Tharn** [comment]
The load time thing sounds like a catch-22 and I honestly wouldn't worry about it if it's an issue introduced by the browser or the *Monkey extension. I prefer userscripts on Chrome and extensions on Firefox, but that's mostly to do with Chrome creating whole new processes for each extension. It would be great to have both.

**Comment by 2tolik** [comment]
How about recommended "usersript manager" (implementation and version) in installation descriptin? 
A valid feedback to userscript managers' authors (at least a single attempt) will be a good step too. 
Happy 2018

**Comment by emmanoelrj** [comment]
Happy 2018. 
Well, the first thing that I need to talk with is your jod is AWESOME! This extension was improved my youtube account since YT+. The resource that I`ve used is the floanting player that this version can`t resize the scale. Please, the next update, put the resize floating player. 
I`m sorry for my bad english. Good luck for your extension work.
