### ISSUE TITLE
Like / dislike buttons in full-screen

### ISSUE THREAD

**Issue by 2tolik** [ParticleCore/Iridium#286]
Currently, to support video/channel via "Like" (thumb-up) users have to exit full-screen and click the button.
It would be natural UX / nice to have corresponding buttons in fullscreen's "[info bar](https://github.com/ParticleCore/Particle/wiki/Features#info_bar)". 

_P.S. If additional keyboard shortcut(s) functionality is possible/planned, then a separate feture request will be filled / noted in comments too._

**Comment by 2tolik** [comment]
There is [UserJS](https://greasyfork.org/ru/scripts/34049-youtube-like-dislike-video-and-skip-ad-keyboard-shortcuts/code) but it does not work alongside Iridium.

**Comment by 2tolik** [comment]
YouTube Like/Dislike [API](https://developers.google.com/youtube/v3/docs/videos/rate)

**Comment by ParticleCore** [comment]
I will never make use of their API due to Google's terrible background of non-transparent data collection as well as - and most important - the limitations imposed by the last major update which would force either to a) purchase quotas to prevent API DoS due to imposed limits or b) tell users to create their own developer account in order to use their own dedicated API quotas.

Neither is a solution I can accept.

**Comment by MattSturgeon** [comment]
I could've sworn that I'd commented this before, but if anyone is interested in getting the [script](https://greasyfork.org/ru/scripts/34049-youtube-like-dislike-video-and-skip-ad-keyboard-shortcuts/code) linked above working alongside Iridium, I proposed a patch [here](https://greasyfork.org/en/forum/discussion/33581/x) a while back.

Basically you just add `videoinfo = (videoinfo.length == 1) ? videoinfo[0].getElementsByTagName("ytd-menu-renderer") : [];` just after line 30 so that it ends up looking like this:

```js
...
  else skipbannerad = null;
  
  videoinfo = document.getElementsByTagName("ytd-video-primary-info-renderer");
  videoinfo = (videoinfo.length == 1) ? videoinfo[0].getElementsByTagName("ytd-menu-renderer") : []; // <-- ADDED HERE
  if(videoinfo.length == 1) {
    buttons = videoinfo[0].getElementsByTagName("button");
    like = buttons[0];
    dislike = buttons[1];
  }
  else
...
```
