### ISSUE TITLE
Pop-Up Player enabled by default after apgrade but button didn't appear

### ISSUE THREAD

**Issue by FengLengshun** [ParticleCore/Iridium#288]
Recently upgraded from the 0.4.2b to 0.4.3b. Pop-up video button didn't appear on the video thumbnails, which confused me. Checked Iridium settings, which has it turned on, but it still didn't appear. Turning it off and then turning it on again fixed it, so perhaps it should be made to be disabled by default?

**Comment by ParticleCore** [comment]
I was able to reproduce this, but it is unfortunately something out of my hands. When the update occurred the associated styles (stored as an external file) were still old, meaning that the new style version hadn't updated yet. As soon as I forced it to refresh then the button appeared immediately.
The option is enabled by default, you just didn't see it because it is set to be invisible by default unless the user moves the mouse over it, however that last hover part was controlled by the new style version, which you very likely still didn't have, causing the button to stay always invisible until you refreshed the page after disabling-enabling the option again.
This won't happen with the extension version since the styles will be version dependent, meaning that once the extension updates then the styles associated to that version will also update without exception.
