### ISSUE TITLE
Saved video position

### ISSUE THREAD

**Issue by Daisenki** [ParticleCore/Iridium#292]
Not sure if it's a real issue or simple question, I noticed that the video position is sometimes saved and sometimes not, I'm now online with a new Firefox profile and made a lot of changes and recommendations from ghacks guys. 

The video should be save the last position after I leave the page or refresh it, but it did not every time. Maybe it's a thing with browser.sessionstore.interval?

**Comment by ParticleCore** [comment]
If you are referring to the time position you were watching before leaving the page then that is something controlled by YouTube itself, not this extension. If this is not the case then please follow the instructions for opening a new issue as requested: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by Daisenki** [comment]
Yes I mean the time position/time code(?) for the current watched video. Sometimes it save the position and resume the video at the last time position and sometimes not. I guess there must be any data in cache or buffer with the time code. 

My thought was I block it with a setting at Firefox and maybe you have any knowledge about the time positions.

**Comment by ParticleCore** [comment]
It's YouTube that memorizes that information, unless you blocked with an adblocker or strict privacy settings (for example) the URL responsible for collecting that data (usually contains the string `watchtime`), in which case YouTube has no way to know where you were last before leaving the video. This is not something browsers track since each website handles video playback in their own way and the same goes for resume.
