### ISSUE TITLE
Three finger tap on video thumbnails toggles audio, while the user only wanted to middle click

### ISSUE THREAD

**Issue by FatOrangutan** [ParticleCore/Iridium#298]
This is on a precision touchpad, Win 10 1709. Iridum 0.4.5b, Violentmonkey 2.8.27, Firefox Nightly.

STR:

1. Enable both `Play videos by hovering the thumbnails` and `Shift key toggles audio on video thumbnail playback`.
2. Hover over a thumbnail and wait for playback to begin.
2. Triple tap on the thumbnail.

You can set Three-fingers > Taps to `Nothing` in Win10 Settings and still reproduce the issue. I have it set to middle click and so the audio begins playing when I just wanted to open the link.

**Comment by ParticleCore** [comment]
As I understand this makes use of a key combination (for example: Shift + Click) specifically configured by the user and for this reason this will not be fixed because changing the key to a different one might cause the same problem you reported for other users that have that key configured for other key combinations.

If the later configuration was just reproducing the middle-click without anything else then the audio would not begin to play, I just tested it with an actual mouse middle-click on both browsers and the audio only plays if I press Shift when the mouse is over the thumbnail.

The fact that you think you set it to "nothing" and it still toggles the Shift action shows that there still is something active linked to either one finger, two or three that is triggering the Shift action, otherwise the thumbnail audio would never turn on, it is not detecting how many fingers are touching, only when the Shift key is toggled.

I would suggest that you make sure you have nothing else configured to trigger during that tap, you can have a macro software running parallel or another Windows option active that is causing this.

**Comment by FatOrangutan** [comment]
>I would suggest that you make sure you have nothing else configured to trigger during that tap, you can have a macro software running parallel or another Windows option active that is causing this.

If I set it to `Nothing` triple tap does absolutely nothing anywhere, not open links etc. I have no macro software running, precision touchpads carry no other settings outside of Win 10 Settings, and I have just reproduced everything in a vanilla Nightly + VM + Iridum.

**Comment by ParticleCore** [comment]
You said this

>You can set Three-fingers > Taps to Nothing in Win10 Settings and still reproduce the issue.

This means that even when it is set to nothing it is still triggering Shift over the thumbnails. Iridium does not track how many fingers you are using, it only cares when you toggle Shift. If it still plays audio after you set triple tap to nothing then that means something is triggering Shift and that something is not from Iridium, but from your side and only your side.

This is unrelated to Iridium seeing that it is only responding to whatever you have on your side causing Shift to be sent to the playing thumbnail. This is not something that I can fix, it is on your side only.

**Comment by FatOrangutan** [comment]
I have further tested things. If I replace `event.which === 16` with `event.shiftKey` in your userscript then everything works as expected. I can't tell why that happens but this confirms what I have been saying that "this is not on my side."

`which` property is deprecated anyway, why are you still using it?

**Comment by ParticleCore** [comment]
Check if your triple tap shows the number "16" by testing it on this page http://keycode.info/

**Comment by FatOrangutan** [comment]
I've been testing on https://dvcs.w3.org/hg/d4e/raw-file/tip/key-event-test.html already, and it shows this weird output when I triple click, while it is set to `Nothing`:

![capture](https://user-images.githubusercontent.com/8336638/35473686-b18c4126-03a9-11e8-9431-c3fdad36e686.PNG)

And yes, your link detects both triple and 4 taps as `shift` while both are set to Nothing. I need more time to test. Hope somebody with access to a precision touchpad could chime in too.

**Comment by ParticleCore** [comment]
You might have another setting for single three finger tap which triggers all of those key modifiers, but are then "ignored" when you tap for a second time, giving the illusion that it did nothing or something else completely different, all of which are completely outside the focus of Iridium already.

**Comment by FatOrangutan** [comment]
>You might have another setting for single three finger tap which triggers all of those key modifiers

Ah yes. So while I had disabled Taps, I had left three-finger Swipes at their default of 'Switch Apps and show desktop'. And yes, setting both to Nothing fixes the issue.

>all of which are completely outside the focus of Iridium already  
  
I agree, but now this can help anybody else running into issues with precision touchpads, which are quite common nowadays. Thanks for the help. I will edit the script locally to map that feature to alt.

**Comment by ParticleCore** [comment]
It will definitely help anyone with a dilemma like yours, I appreciate you sharing it here so that it can help others in the future.
