### ISSUE TITLE
Floating Video Player Size

### ISSUE THREAD

**Issue by IRMaNu** [ParticleCore/Iridium#307]
Browser Name: GooGle Chrome

  Browser Version: Latest (64.0.3282.119)

  Operating System: Win 10

  Software Type: Script

  Software Version: 0.0.1

  Userscript Manager: Tampermokey

  Userscript Version: 0.0.1 

  Problem Description: If you Scroll down with Floating Player active, and scrolle back up, the Player is in the middle of the Screen/Browser, not on the normal Position

  Steps to reproduce: Scroll Down, scroll Back up

  Additional details: If you enter Fullscreen, and disable it again, it's on normal Position

**Comment by ParticleCore** [comment]
The player is restoring its normal size correctly on my end. Please follow the troubleshooting guide as requested before opening the issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug#troubleshooting

**Comment by rhn94** [comment]
I had the same problem; followed troubleshoot guide, where it said to create new chrome profile. Problem didn't arise while using new profile. Went back to my profile after restarting chrome and it went back to working as normal. 

I have a lot of custom settings and some extensions, so I wasn't able to narrow down why the problem was caused. Will try to report back again.

**Comment by theorist-complex** [comment]
This actually happened to me, too, using Waterfox, though instead of the middle of the screen, the video was far left of the browser. This happened in a single tab, multiple times, but I was unable to reproduce in other tabs, and once I refreshed the "problem" tab, the issue fixed itself and hasn't happened again since.

**Comment by IRMaNu** [comment]
I fixed it, but not with the troubleshoot, i actually don't know how i fixed it, i restartet the browser several times and it worked again, i'm gonna write something if i manage to reproduce the glitch again.

**Comment by ParticleCore** [comment]
It could very well have been a YouTube change that was causing problems and has been reverted once you restarted several times.

**Comment by theorist-complex** [comment]
This has happened to me again. Just thought I would post a screenshot of what it looks like in case it helps any.

https://i.imgur.com/fqpCoQP.png

I'll try to keep the tab open in case I can answer any questions or whatever.

**Comment by ParticleCore** [comment]
@theorist-complex You have modifications on that page that Iridium is not responsible for and that problem might be a consequence or interference caused by other Scripts, Extensions or Styles, which is why it is important to test the problem following the troubleshooting instructions provided before.

If I can't reproduce this problem then I can't fix it.

**Comment by BlueNinja0** [comment]
This happened to me too, though it seemed to only trigger on a specific Youtube video. Other videos did not trigger the bug.
I don't remember which it was, but I'll post here if it happens again with the offending video's URL.
