### ISSUE TITLE
[Bug] Youtube Error 404 monkey appears in iridium settings

### ISSUE THREAD

**Issue by Nallat** [ParticleCore/Iridium#323]
Browser Name: Google Chrome

Browser Version: 64.0.3282.140

Operating System: Windows 10 Fall Creators Update Build 16299

Software Type: WebExtension

Software Version: v0.0.2
![3b9d2d1c-699a-4dbb-a30e-7eb618c6a71d](https://user-images.githubusercontent.com/33554398/35770961-8522ec44-0925-11e8-80b2-29f68ba163f0.png)
![f6014252-0447-45cc-ad64-ac68aaceb2e8](https://user-images.githubusercontent.com/33554398/35770962-854292c4-0925-11e8-9512-1ba8a022f9de.png)

**Comment by ParticleCore** [comment]
It is working correctly on my side with Chrome:

![ss](https://user-images.githubusercontent.com/9222661/35771061-3f4aaebe-0916-11e8-93af-a5ff38e0a5df.png)


In your previous issues you shared the entire browser screenshot, now only the page itself is what is shown and you mistakenly added `WebExtension` together with `Chrome` when the only Firefox uses WebExtensions.

I hope that you did not just crop screenshots from Vivaldi in an attempt to make me think that this problem is also present in Chrome seeing that I already explained that there is no support for Vivaldi. If that is the case I will have to block you from this repository as per the rules.

Please press F12 or right-click and select `Inspect element` anywhere inside that page to open the console, select the `Elements` tab and take a screenshot of the page and the console opened and sent it so that I can see what might be working incorrectly.

**Comment by Nallat** [comment]
@ParticleCore 
![g](https://user-images.githubusercontent.com/33554398/35771275-55a3e9d2-092a-11e8-9fab-406014a72ed0.png)

**Comment by ParticleCore** [comment]
That's only for Firefox ([it is literally linked under the Firefox section only](https://github.com/ParticleCore/Iridium/wiki/Download)) and I can't understand how the version did not increment, my appologies.

However, you are now showing that you have Ghostery installed, which you did have on [Vivaldi](https://user-images.githubusercontent.com/33554398/35769227-3a33a63c-0908-11e8-9bd5-f9e0a1801396.png), but not on [Chrome](https://user-images.githubusercontent.com/33554398/35769743-e85eae30-090f-11e8-8b03-2f378df4e110.png), which makes me believe that you really are cropping images from Vivaldi and saying that it is from Chrome.

I also asked for a full screenshot showing the HTML in the console from the page and you did not provide that.

Seeing that I cannot reproduce this problem with the same setup and that you started cropping the images to leave the browser UI out of sight I can only conclude that you are trying to deceive me into thinking that your Vivaldi bug is present on Chrome as well when it really isn't and that is something I don't appreciate because it is wasting my time when I could have been doing something more productive.

It is also a pointless effort because I cannot fix a problem that I cannot reproduce, that means that even if your Chrome browser was really showing a real bug, I would not be able to fix it on my end until it happened to me as well.
