### ISSUE TITLE
The k button doesn't work anymore

### ISSUE THREAD

**Issue by briank6932** [ParticleCore/Iridium#33]
The pause functionality for the k button doesn't work anymore with player shortcuts always on or off.

**Comment by ParticleCore** [comment]
The k button is working correctly on my end. Please follow the instructions for reporting a bug as requested: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by ParticleCore** [comment]
Correction, I was able to replicate the problem and it is a YouTube problem, not related to the extension. The same problem exists with the extension turned off. Current workaround is to click somewhere outside the player area so that it loses focus or use the spacebar until the problem is fixed.

This problem only occurs when the video player is active/selected and press the k button. The action is always play when this happens, never to pause.

Please help report this bug to the YouTube team via the Send feedback link available on the menu located on the top right corner of your page or near the end of the left sidebar menu.
