### ISSUE TITLE
Autoplay settings interferes with Firefox's media.block-autoplay-until-in-foreground

### ISSUE THREAD

**Issue by gappleto97** [ParticleCore/Iridium#353]
When autoplay is enabled, and `media.block-autoplay-until-in-foreground` is enabled, the expected behaviour is to load the video element and buffer it, but not play it. When both of these options are set under Iridium, the video plays regardless of whether it reaches the foreground. This did not happen in the days of YouTube+, which makes me think it's happening because of Iridium, and not a Firefox update.

**Comment by ParticleCore** [comment]
That is an unstable browser option for which its behavior cannot be accounted for from a simple userscript perspective.  
With YT+ there is a completely and radically different YouTube layout than Iridium so they shouldn't be compared in this way without taking that into account.  
You also did not say whether or not this problem was still happening while Iridium was turned off, you clearly did not follow the instructions before opening an issue as requested: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

But regardless this is something that I am not willing to "fix" due to the inability to provide autoplay control in any other way.  

If the browser shouldn't let it play until it is in foreground, but it still plays regardless, then that is a browser bug since that's its own responsibility which is clearly not working and this should be reported to Mozilla.

**Comment by BlueNinja0** [comment]
This is not happening to me in Iridium 0.0.9 and FF 58.0.2
With autoplay enabled and media.block-autoplay-until-in-foreground enabled, a video opened in a background tab is buffered and not autoplayed, as is expected.
