### ISSUE TITLE
please add @downloadURL support

### ISSUE THREAD

**Issue by gofirst2220** [ParticleCore/Iridium#37]
see title. 
If you implement the `@downloadURL` line, to the metadata block, Greasemonkey and ViolentMonkey will actually find updates and to install it.

Without it, it may not find any updates, so please add it.

I found out about this when it didn't auto-update it.

**Comment by JourneyOver** [comment]
Iridium has been auto-updating just fine on my end on several computers, and I don't have the `@downloadurl` line at all.

**Comment by gofirst2220** [comment]
@JourneyOver , well, `@downloadURL` kinda works. it works well if it comes from original source like Github. my other scripts that I use, without this, won't auto-update at all because they don't come from original hosted source. I noticed that sometimes it doesn't check for updates properly, sometimes it doesn't.

**Comment by ParticleCore** [comment]
`@downloadURL` is only useful if the userscript is intended to be served from one place alone. This means that when served on different hosts either that url will have to be manually set for each host version (not an option since I intend to serve the same userscript on other hosts as well) or ditched completely. By default I have always let the userscript managers handle this on their own and update according to where the userscript was downloaded from and I have never met any issues with this, which is how the normal behavior has been:

>If @updateURL or @downloadURL are not provided, the URL that the script was downloaded from is used instead.  If the @downloadURL is not provided and the install URL is not known, updates will never be applied.

http://www.greasespot.net/2012/02/automatic-script-updates-come-to.html

If yours happens to not be working as expected then that is a problem with your userscript manager and you should report it to its developer.

**Comment by Kontorted** [comment]
en.savefrom.net is a good place for a download option.

**Comment by ParticleCore** [comment]
@Kontorted That is not what this issue is about, the downloadURL is not for downloading videos, it is for the userscript to be able to update itself more reliably.
