### ISSUE TITLE
UserJS 0.4 -> 0.1.0 udpate problems

### ISSUE THREAD

**Issue by 2tolik** [ParticleCore/Iridium#386]
Tampermonkey v4.5 for Chrome (65.0.3325.146 (Official Build) (64-bit) for Win10) does not update 0.4.x version to latest 0.1.0 of "master" showing warning that roll-back in terms of versions has occured. It does not update script version even after manual trigger. 

-// @version         0.4.7b
+// @version         0.1.0

Maybe it meant to be 1.0.0 instead ?

**Comment by ParticleCore** [comment]
The beta branch was never meant to branch into master automatically, they were made separately on purpose. The change must be made by the user consciously because there are those that could not want it to change out of beta on its own and for this reason, and others, the version was reset upon release.

**Comment by 2tolik** [comment]
If you going to continue with beta(s), then it might make sense of a user to jump back and forth between master<>beta. In that sense keeping incremental version (alpha 0.3, beta 0.4 and release 1.x as of now) sounds like a good idea. None of my business, just saying / could not figure out reason of separate versioning and 0.1 for a release.

**Comment by ParticleCore** [comment]
There are no more beta versions, it was only for development stage only. Once it reached release the beta ended.
