### ISSUE TITLE
wrong quality

### ISSUE THREAD

**Issue by lajaso** [ParticleCore/Iridium#398]
Browser Name: Google Chrome

  Browser Version: Versión 65.0.3325.181

  Operating System: windows 10

  Software Type: chrome extension

  Software Version: 0.1.1

  Problem Description: wrong quality

  Steps to reproduce: select 720p is 480, 480 is 360

  Additional details: 
![bug](https://user-images.githubusercontent.com/28314717/37860681-ca75afb0-2ee7-11e8-90a2-05e746778f3b.jpg)

**Comment by ParticleCore** [comment]
Can't replicate, the quality options are assigned to the correct label:

![ss](https://user-images.githubusercontent.com/9222661/37862488-1ec75dca-2f3d-11e8-940c-58ebdfc2580b.png)

The Spanish locale is also using the correct structure:

https://github.com/ParticleCore/Iridium/blob/4bab3b7ec0f185069040fc0d43e7c51cd3e432b0/i18n/es_MX.json#L116-L127

You might have modified it yourself and messed up that part, make sure you follow the troubleshooting steps as requested before opening the issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by lajaso** [comment]
the error occurs only when I disable the local language.
![bug1](https://user-images.githubusercontent.com/28314717/37867815-ec8bef9c-2f5a-11e8-99a5-27f1547c4034.jpg)

**Comment by ParticleCore** [comment]
When you enable that you are telling the extension to use the language file that you modified, which in this case has an error in the quality settings label order.

The first Spanish locale does show that error:

https://github.com/ParticleCore/Iridium/blob/a8072f64200d6850f5a83ba393968be4d049f799/i18n/es_MX.json#L79-L89

But it has already been fixed by the same user that created the locale. You can edit to fix your locale as well by clicking on the `Español (Latinoamérica)` button that is in that screenshot.

Either way it is something you have to fix because this has already been fixed here and your locale file can only be edited by you.

**Comment by ParticleCore** [comment]
@lajaso I see what has happened, the locale fix was only made 6 days ago, it probably hasn't past enough time for Iridium to check for an update, which is set to check every week. You can reset your settings if there isn't nothing much you need to backup, or you can backup your settings, remove the locale (it will be inside your settings), load the settings without the locale and Iridium should download the fixed locale version.

**Comment by ParticleCore** [comment]
Thanks to this issue I discovered other locales with wrong position for the Auto label, thank you for bringing this to my attention.
