### ISSUE TITLE
Comment section appears to be ready only after the video starts playing

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Iridium#408]
Does not appear to be consistent, needs more investigation.

**Comment by Atulin** [comment]
Might have something to do with the full browser being turned on. Noticed this behaviour on videos that are opened after full browser was enabled in a different tab.

**Comment by Auscent** [comment]
It's been happening to me and I've never had full browser on in any video.

Doing a bit of investigation myself it seems related to video autoplay, enabling "Play Videos Automatically" in Iridium the problem doesn't appear. With autoplay disabled I messed around with the Iridium code with my limited JS knowledge (and of YT's code) & debugging skills and narrowed the problem down into the experimentsGetter function for disabling autoplay which when I commented out caused the video to start buffering but pause straight away with the comments appearing. Setting a breakpoint in experimentsGetter after the matching condition it's only ever triggered for a match with the vM.Xc property, and setting this property to false causes the issue. This property only seems to be used in two conditions the second of which calls the function S_ in base.js (line 41402 in Chrome formatted file) when either vM.Xc or vM.Zc (mutedautoplay) are true, this function deals with player initialisation which must also be linked to comment initialisation somewhere as they don't load unless S_ has been called. I called it quits from here since I don't much feel like digging through the code any longer to find out where & how the comments are loaded but hopefully this may help if you haven't already figured out the issue yourself.

**Comment by ParticleCore** [comment]
It only happens in Chrome, for now, and it is definitely related to autoplay control. YouTube has a specific order of loading parts of their page, with comment section being now linked to load after the video starts playing. This might be a tricky one to fix.

**Comment by Matthewus** [comment]
It happens in Firefox (59.0.2) too.

**Comment by ParticleCore** [comment]
Closed in https://github.com/ParticleCore/Iridium/commit/491a8ff344f2440a7240d1969526b6843ba1af7a
