### ISSUE TITLE
YouTube has begun implementing their native always visible mini player, Iridium version marked for removal

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Iridium#412]
YouTube has been slowly releasing their implementation of the always visible mini player: https://www.androidpolice.com/2018/03/22/youtubes-miniplayer-bar-test-lets-keep-watching-video-read-comments/

For that reason I am considering dropping this feature from the extension seeing that the focus of this extension is to add features that I find to be useful and YouTube doesn't have.
Now that the mini player is about to be released by YouTube it becomes redundant to keep this feature on the extension.

![ss](https://user-images.githubusercontent.com/9222661/38141106-39fad926-3426-11e8-9426-b070707221ac.png)

Both mini players are not compatible with each other so the feature is marked for removal.

A possible alternative is to offer the option to disable YouTube's implementation and use the Iridium version, but I would have to see if it doesn't require too much trouble making it not worth doing it.

**Comment by Auscent** [comment]
> A possible alternative is to offer the option to disable YouTube's implementation and use the Iridium version, but I would have to see if it doesn't require too much trouble making it not worth doing it.

I would be for this. I really don't like their implementation of a fixed bar at the top with additional pinned stuff I don't care about, I like the ability to move the video around and changing its size (I know Iridium doesn't include a resizing option but I added a hard-coded size of 800x450 to my installed userscript). Of course completely understandable if you feel it's too much trouble to keep around, as another alternative there's the possibility of extending their implementation to disable the additional items and add the ability to move & resize the player though I could see this potentially being even more troublesome than keeping your implementation around.

**Comment by thekcool** [comment]
I'd also prefer keeping the Iridium version as an alternative to the YouTube version. A lot of static players like the YouTube version are UGLY YOU AIN'T GOT NO ALIBI UGLY! Plus I prefer the ability to move the player, if I choose to use the mini player at all, to some other part of the screen on the fly.

**Comment by Flo0fy** [comment]
As the others have said I would also want to keep the Iridium one too.

**Comment by FPRSergio** [comment]
The official Youtube mini player is not reaching everyone, I don't have it yet.

**Comment by jrial** [comment]
Preliminary feedback, as I don't have the new YT floatie yet: from what I've seen in screenshots, it doesn't look too shabby. But the advantage of Iridium's implementation is that it offers you the choice of where to put it.

Personally, I could probably do without Iridium's floating video player. But I haven't experienced YT's implementation yet, so I don't know how frustrating that will be to use.

Also, is it just me, or does Iridium's implementation work on some other video sites as well? I've seen the floating video in the lower right on other sites too, but I was never sure whether it was due to Iridium or if it was just the site that implemented the same thing, and chose the same location to put the floating player in. If the former is the case, that would tip the balance in favor of keeping it in Iridium.

**Comment by ParticleCore** [comment]
@jrial Iridium is strictly for YouTube main domain, other websites have implemented this kind of behavior before this extension existed because they find it useful (users know where the playing video is when they enter the webpage instead of trying to find it just to stop its playback).

**Comment by Eisys** [comment]
https://twitter.com/techkrest/status/981995248531492864
And now this as well..

Is it possible youtube is just copying features from Youtube+/Iridium?

**Comment by ParticleCore** [comment]
@Eisys Not at all, they already had it on gaming.youtube.com, if anything it would be more correct to say that Iridium copied YouTube, except the inspiration came from different websites, but the idea is the same.

This is actually good, because as I explained the goal of the extension is to offer features YouTube does not have. With these new additions I will have the option to either "enhance" them or drop the Iridium versions and focus on new features.

**Comment by Eisys** [comment]
Ah, okay. I never visit the gaming side so didn't know.

As for feedback, I too would like Iridium's version to stay. Simpler and moving it around makes it better but at the same time, deprecating them might make way for new and better features or whatnot. I'm sure people would get used to the YT version and it'd be easier on you.

Also a question about Youtube+, I know it's not supported any more.
The miniplayer goes blank/glitches like this:
https://i.imgur.com/B0EzRF8.gifv
Hanging on to the old layout so I just wondered if this is a bug or something on my end. Thanks.

**Comment by ParticleCore** [comment]
@Eisys I honestly cannot tell, I've never seen anything like that before.

**Comment by milklineep** [comment]
I prefer the Iridium version honestly. If the width could also be customized it will make it so much more useful than YouTube's. Also the feature didn't roll out to me yet so I was surprised when Iridium stopped showing the floating player.

**Comment by NovaViper** [comment]
I don't like the Youtube version.. I prefer the on the corner, sort of incognito version that Iridium uses.

**Comment by DallasBelt** [comment]
+1 for Iridium version :D

**Comment by shogunreaper** [comment]
youtube's version takes up too much space.

**Comment by vertigo220** [comment]
I second what everyone else has said, but in addition I will just add that, IME, third-party implementations of features are usually better than Google's. They have a habit of doing this half-baked, not listening to users and implementing things the way they want instead of the way their users want, and abandoning projects. If this were to be dropped from Iridium, even if Google eventually improved their own feature, I would just not want to rely on them not messing it up or dropping it.

Also, I'd like to know how to manually resize Iridium's floating player. I miss the ability to resize it that YouTube+ had (I see that it's a planned feature for Iridium, but if I can do it manually, that would suffice for now).

**Comment by dan019** [comment]
I consider having the ability to disable the mini player another good option. I recently was one of the lucky few who got pushed this new feature. However I could find no easy way to disable it, which bothered me. Good luck!

**Comment by mtcjayne** [comment]
When I noticed YouTube doing their own popup window I immediately went to disable their version so it wouldn't interfere with Iridium because I prefer the added benefit of being able to move the popup around.
