### ISSUE TITLE
Privacy policy of Iridium

### ISSUE THREAD

**Issue by diswardeepak** [ParticleCore/Iridium#446]
I use the Iridium chrome extension. I couldn't find the privacy policy of Iridium on either the chrome web store listing or the github page. Can the owner share it?

**Comment by ParticleCore** [comment]
There is none specific to the extension since it does not collect any user data. At best it uses/shares the same as the Chrome webstore since the webstore itself is probably collecting analytics information by default.
On the other hand, the userscript version uses/shares the same policy as CoinHive for the same reason as the Chrome webstore.
