### ISSUE TITLE
Fullbrowser player shows Youtube UI behind it

### ISSUE THREAD

**Issue by IamCarbonMan** [ParticleCore/Iridium#451]
For example: 
![image](https://user-images.githubusercontent.com/16262064/40005838-ce165d34-574d-11e8-8373-e1c425ba49d7.png)

It would be nice if the player had a black background like in old Youtube+

**Comment by ParticleCore** [comment]
Please follow the troubleshooting instructions as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by IamCarbonMan** [comment]
I followed the listed steps and didn't see any change. The YouTube UI is still visible behind the video.

**Comment by ParticleCore** [comment]
Please read the instructions again, there are steps that you did not follow. I don't know which browser you are using, the version,  which Iridium version and type you are using, etc.

I cannot replicate your problem and judging by the screenshot you have a heavily configured browser, which is very likely the cause of your problem and not Iridium, which is why it is important to follow all the troubleshooting steps, including the step where you disable all extensions and scripts except Iridium to see if the problem is still there after restart.

**Comment by IamCarbonMan** [comment]
Browser Name: Chrome

Browser Version: 66.0.3359.181

Operating System: Windows 10

Software Type: Extension

Software Version: 0.1.4

Problem Description: YouTube UI is visible behind the fullbrowser player

![image](https://user-images.githubusercontent.com/16262064/40141192-015d749e-590a-11e8-9830-e390a1ec295e.png)

Steps to reproduce: Open any video in fullbrowser mode

**Comment by ParticleCore** [comment]
Same browser version, same video just to be sure and tested with extension version and userscript version as well, the background is covered in black as expected:

![ss](https://user-images.githubusercontent.com/9222661/40147758-849954d6-595a-11e8-8dc9-db7f09e26d7a.png)

By your screenshot I can see that you are still using your customized browser. One of the troubleshooting steps specifically explain to check if the problem exists with a blank browser profile:


> - Create a new browser profile and install only Iridium, see if the problem still persists. New profile instructions:  [Firefox](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles#w_starting-the-profile-manager) | [Chrome](https://web.archive.org/web/20160915221807/https://support.google.com/chrome/answer/142059)

I also noticed that you have a Red subscription, please check if the issue is also still present while logged out. I don't have a Red subscription so I cannot confirm this on my side.

**Comment by IamCarbonMan** [comment]
OK, so I tried this in a new profile and then again in my default profile and pinned down the issue, and it apparently is YouTube Red. When I sign in with my YouTube Red account the background is transparent, when I sign into another account that doesn't have Red it is black.

**Comment by IamCarbonMan** [comment]
The fix I'm using for now is a userstyle like so:

```css
.html5-video-player {
    background: black;
}
```
