### ISSUE TITLE
Youtube videos are moved off screen

### ISSUE THREAD

**Issue by qissqiss** [ParticleCore/Iridium#472]
When I scroll the page down far enough for the video to go off screen Iridium moves the video to the top right-hand corner of the browser window, all I can see is the bottom left-hand corner of the video screen with the play and pause button. There is a massive Black box where the video should be, there is nothing I can do about this issue, I have tried changing settings in Iridium and firefox, nothing fixes it, I have to reload the page and then scroll through the video to continue watching it.
Windows 7
Firefox 56
Iridium 0.1.5 Add-on

**Comment by ParticleCore** [comment]
Please follow the instructions before opening a new issue as requested: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by qissqiss** [comment]
Hey, I don't really care about your stupid rules, I came here and signed up to let you know there is an issue, I don't use Iridium anymore because you are making me jump through hoops just to report a fucking issue.
I told you the problem with the add-on, if you don't want to fix it I don't give a shit, I was just letting you know, ok? good day. Don't respond to this.

**Comment by ParticleCore** [comment]
I don't have this issue, so it is impossible for me to fix it if I don't have more information like a screenshot. It is also possible that this is an issue caused by other extensions or configurations you might have that are causing this conflict only on your side, which is why it is important to follow the troubleshooting instructions.

You don't have to follow anything and neither do I so if you don't really care, why should I?
