### ISSUE TITLE
Feature Request: Choose default playback speed 

### ISSUE THREAD

**Issue by eyescovered** [ParticleCore/Iridium#476]
I watch everything at 1.25 speed, so it would be nice to not have to change that setting everytime I open youtube. Thank you.

**Comment by Eisys** [comment]
In the meantime, you can use this extension; [Video Speed Controller](https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk)
[Firefox version](https://addons.mozilla.org/en-US/firefox/addon/videospeed/)

I watch at all sorts of speeds from 1.25x to 2.5x and this extension is a godsend. It also remembers the last speed you used so you can just set it at 1.25 forever.

**Comment by eyescovered** [comment]
thanks, this works great!

**Comment by Jowat97** [comment]
@ParticleCore I don't think that it is a good idea to use multiple Addons if we can use one instead. So wouldn't it be possible for you to add this function? So many ppl asked for it.

I would really like to use the intern youtube playback function instead of the HTML one, which most playback-speed addons use. Because if the speed is set via HTML, you can't see and change it within YouTube, instead you need to use the Addon again.

It isn't hard to implement this feature.
You can set the Speed by using Javascript Commands provided by Youtube:
document.getElementById("movie_player").setPlaybackRate(2);
With this function the intern PlayBack-Control by YouTube will be used. So you can see and set it also via the Youtube-Player Settings.
