### ISSUE TITLE
Time of upload of a video

### ISSUE THREAD

**Issue by miticocampo** [ParticleCore/Iridium#482]
Most of the times, I am interested in the exact time (hour and minute of the day) of upload of a video, to know more about strategies that some channels are using.
I am getting this data only from this website https://citizenevidence.amnestyusa.org/
Is it possible to add the possibility from the settings of the extension to choose whether to display this extra data?

thank you so much in advance

**Comment by ParticleCore** [comment]
It is somewhat possible, I've researched this before in the previous extension. YouTube sends the LMT (last modified timestamp) for each video quality and audio stream, but unfortunately that does not equate to the exact upload time since the creator can modify his video after upload. We'll see, it is something that I am interested as well, but left it at that.
