### ISSUE TITLE
Please add the "classic YouTube" feature

### ISSUE THREAD

**Issue by mooms06** [ParticleCore/Iridium#513]
https://www.reddit.com/r/firefox/comments/91hbkw/youtube_page_load_is_5x_slower_in_firefox_and/

https://twitter.com/cpeterso/status/1021626510296285185

https://openuserjs.org/scripts/Cpt_mathix/Youtube_-_Restore_Classic
or
https://addons.mozilla.org/firefox/addon/youtube-classic/

The issue is: once the script or the addon is installed, Iridium don't work anymore on Firefox.
So either add the feature in Iridium, or make it compatible with the "old" YouTube.

Thank you.

**Comment by ParticleCore** [comment]
Iridium was built specifically for the new YouTube version, this would defeat the entire purpose of the extension.

**Comment by mooms06** [comment]
Too bad, then I will not use Iridium anymore, because I prefer a fast loading for YouTube.

**Comment by mooms06** [comment]
Do you have used YouTube with Firefox (or Edge) lately ?
Even with a 1Gb fiber connection, the page takes several seconds to load (the video works fine though).
That's the real issue here, and the "classic YouTube" is a workaround for that.
The issue will be fixed by Google eventually, but in the meantime, we can't use Iridium & the workaround, so we have to make a choice.

**Comment by PoorPocketsMcNewHold** [comment]
@mooms06 Indeed, The thing is, Iridium has been designed with the new yt design in mind, The fact that it's not working with the script is really necessary due to it, even in the period when youtube offered the possibility to came back to the old design, It wouldn't work at all.
It's also really not a great idea to really work on the support of it, as since YouTube is pushing the new design, The old one won't be here for long _(I mean, If i could, i would want to revert to the old 2008 design of the youtube accounts)_ 
Maybe using the latest fork of Youtube+ Freedom _(I'm not wrong on the name ? Is that the correct name of the old script ?)_ could work, But i don't know if it's still available to use/download somewhere.

**Comment by PoorPocketsMcNewHold** [comment]
Well, I've just tested it. [And indeed, Youtube+ is working perfectly](https://lewd.pics/p/?i=dWsQ.jpg). So, As Youtube+ was Iridium before the new Youtube Interface came. I guess we fixed your issue. @mooms06

**Comment by mooms06** [comment]
Indeed, installed the script, and it's even better since YouTube+ was translated !
I had thought of using it but didn't remembered the name before Iridium...
Thank you !
