### ISSUE TITLE
YouTube changed their video player to be dynamic in size

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Iridium#524]
As some of you already noticed, the video lately has not been resizing correctly in fullbrowser mode or mini player mode.
After further experimenting the conclusion is that YouTube is either experimenting the player to fit the video itself (not all videos are 16:9) or it's a bug.

As you can see this is how the video player should look like:

![ss1](https://user-images.githubusercontent.com/9222661/43357574-58eb9338-9273-11e8-9b18-c5a50eb378fe.png)

But now this is how it looks like:

![ss2](https://user-images.githubusercontent.com/9222661/43357576-6134827a-9273-11e8-9cb6-37c718d0e634.png)

For any video that doesn't have artificial black borders appears the player is fitting to it's original size, but this is a problem for some videos that are taller than wide, for example:

![ss3](https://user-images.githubusercontent.com/9222661/43357601-b4721056-9273-11e8-83e9-787905b6e8a9.png)

And this only gets worse (or better if you're watching on a phone or tablet) the taller the video is:

![ss4](https://user-images.githubusercontent.com/9222661/43357616-ff252d72-9273-11e8-82e3-9510b205de69.png)

All of this to say that a fix for the scaling issue is already found, but if this change YouTube made is not intentional then it might break again soon and that this player behavior is not caused by Iridium but by YouTube itself

**Comment by Paulaob79** [comment]
Thanks! It fixed the problem and also the new big size player "feature". :)

I will report if I see the bug coming back.

**Comment by ejaedesign** [comment]
Is this the reason why on a pop-up window, the bottom of the video is cut off if the window is resized?

Before, if the pop-up window is resized black bars would properly appear to keep the aspect ratio and avoid cropping the video. Now, the bottom of the video is simply cut off. 

Thanks!

**Comment by ParticleCore** [comment]
@ejaedesign Can you please follow the instructions: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by BreadYogurt** [comment]
Is there a way to disable this fix? I like the dynamic player sizing and if there's an option to reenable it in the Iridium settings, I can't find it.

**Comment by ParticleCore** [comment]
@BreadYogurt At the moment I have not yet implemented an option to toggle it.

**Comment by YoBii** [comment]
This is not how it works for me. Using Firefox or Chrome.

Even when I disable Iridium and any other possibly conflicting add-on.

For me the YouTube player itself automatically switches to use the full browser width but not height. This results in black bars on the left and right of the video frame. First I thought this is caused by my monitor's resolution, which is 1440p, because the video will not stretch beyond native resolution.
But even with 4k videos and at 1080p resolution it"s the same. 

I'd really love to either have no black bars around the video frame (video frame size = player frame size) and/or fit the video frame to the entire width/height of the browser frame.

[Screen 1](http://tinyimg.io/i/EcV8Dgd.PNG)
[Screen 2](http://tinyimg.io/i/aUpeuXr.PNG)

![image](https://user-images.githubusercontent.com/22051355/47926475-ef057700-dec0-11e8-96c8-7dd91d366ebd.png)

![image](https://user-images.githubusercontent.com/22051355/47926389-b82f6100-dec0-11e8-9ffd-f5508b163ccc.png)

**Comment by ParticleCore** [comment]
That's unrelated to this issue and is how YouTube works in Theater mode.
