### ISSUE TITLE
Malicious browser extension attempting to pass as Iridium

### ISSUE THREAD

**Issue by sm-Fifteen** [ParticleCore/Iridium#566]
Hi, I'm not an Iridium user myself, but just thought I should let you know that I've had a fake browser update popup attempting to install a firefox extension on my browser. I've reported the website in question to Mozilla and downloaded the XPI to see what kind of extension this was, and the manifest and iridium.user files linked back here, so it appears parts of it were reused from the code of your extension, but the permissions are off and the code for ij.js and background.js is heavily obfuscated.

```json
{
    "manifest_version" : 2,
    "name" : "Iridium",
    "version" : "0.2.1",
    "description" : "YouTube with more freedom",
    "default_locale" : "en",
  
    
    "background": {"scripts": ["js/background.js"]},
	
    "content_scripts" : [{
            "matches" : ["<all_urls>"],
            "js" : ["js/ij.js"],
            "css" : ["css/Iridium.css"],
            "run_at" : "document_start"
    }],

    "permissions" : ["storage","tabs","webRequest","webRequestBlocking","activeTab",
                    "<all_urls>","http://*/*", "https://*/*",
                    "unlimitedStorage", "cookies"
    ]
}
```

I'm not entirely sure if I should link to the malicious website in question, but I can probably at least attach the XPI file in question. 

[ww.zip](https://github.com/ParticleCore/Iridium/files/2376971/ww.zip)

I've taken the time to deobfuscate the content script by hand, and it definitely doesn't seem like the code on your github repository to me.

[ij-malicious.js.txt](https://github.com/ParticleCore/Iridium/files/2376976/ij-malicious.js.txt)

I don't know if the maintainer(s) of this project can really do anything about this, but I figured they'd want to know about this.

**Comment by sm-Fifteen** [comment]
Just for good measure, here's the malicious website that promps you to install said extension. I wouldn't advise anyone to try and go there (it automatically goes into full-screen mode and checks if it still is to make sure you can't exit), but it might be good to know anyway : `https://s3.amazonaws.com/ghred/ca/index.html`

I've already filed a phishing report to Mozilla about it.

**Comment by ParticleCore** [comment]
I appreciate the due diligence you took with this and bringing to my attention as well. Reporting it to Mozilla is the right thing to do since they can blacklist the signature that is associated with that webextension seeing that they now need all to be signed in order to be installed on the users's browser, meaning Mozilla can "kill" it when necessary.

If you can, please link the website as well so that this can gather more awareness for any other users under the same situation unaware of what it might be or what they can do about it.

I have also took the liberty to scan the zip you shared so users interested in inspecting the code you shared are not tricked into a wolf-among sheep kind of situation in case you were trying to pass a virus:

[ww.zip](https://github.com/ParticleCore/Iridium/files/2377045/ww.zip)


https://www.virustotal.com/#/url/62158cf509f70ee8716036d07d185947721c62e5dbf4589ce49832fbed12916f/

**Comment by ParticleCore** [comment]
It appears the malicious webextension isn't even signed, fortunately this means vanilla Firefox would not allow the installation.

Out of curiosity and if you are willing to, could you described the actions that took for you to come across this situation?

**Comment by sm-Fifteen** [comment]
Nothing in particular, it's one of those aggressive pop-ups you sometimes see on websites that are a bit desperate for ad revenue sources (more specifically tubeunblock.me, which I rarely use to get around region-locking on youtube).

Makes me ponder why I ever stopped using NoScript. ;)

**Comment by ParticleCore** [comment]
The `background.js` file has been completely modified and appears to be designed to turn the user's computer into a zombie machine, probably to be part of a botnet of sorts.

I don't think there is any danger for any users using vanilla Firefox since it does not allow the installation of extensions that are not signed unless users have turned off that protection on their browser.

**Comment by ParticleCore** [comment]
It couldn't be reported because the provided add-on does not have a guid with it. I will however report that guid as potentially belonging to the add-on exposed in this issue. Thanks.

**Comment by wagnerand** [comment]
For the record, that file was signed (see the `META-INF`folder inside the extension). If you can't figure out the ID, that is no problem, just report it to us and attach the entire file.

Note that a report has already been filed for this add-on at https://bugzil.la/1497161

**Comment by ParticleCore** [comment]
Thanks for the input, I see it has been dealt with, I'll be closing this issue now.
