### ISSUE TITLE
Fix Iridium mini-player incompatibility with YouTube miniplayer

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Iridium#575]
YouTube appears to have released its own mini player equivalent to the always playing feature of Iridium. While it does not break the playback capability so far, it is not a good experience.
Will try to see if I can make it work with the current version or remove the feature completely.

**Comment by Acid-Crash** [comment]
Hi, 
mini player provided by your extension seems to have more functionality compared to the one from Youtube (ability to change position, etc).
Maybe you can simply add a toggle switch (in the settings menu) to disable the icon (Youtube one) that toggles min player...

**Comment by thepcwiz101** [comment]
Miniplayer that implemented by youtube themselves doesn't even work for me for some reason.

**Comment by Fannste94** [comment]
Add an option to disable or enable the mini player

**Comment by m4dpr0ph3ss0r** [comment]
A quick hack/fix for the 'x' not stopping playback and audio continuing to play after closing the mini player is to pause the playback first before clicking the 'x'. This will allow the mini player to close and stops the audio.

**Comment by AzimsTech** [comment]
> Add an option to disable or enable the mini player

This.

**Comment by Rainyan** [comment]
> Add an option to disable or enable the mini player

Apologies for the bump, but is this option still available? I can't seem to find it in the extension preferences. My typical experience consists of:

* Enter a video page
* Go back to previous page with browser navigation (Firefox)
* Realize it's still playing audio from the previous page in the background (no mini player to be seen but the sound keeps on playing; this seems to be a YT "feature" since years by now)
* Manually refresh the entire page or close/reopen the tab to make it stop playing noises against my will

which is not ideal in terms of user experience, not that YouTube cares.
