### ISSUE TITLE
Videos Won't Load

### ISSUE THREAD

**Issue by rachael7** [ParticleCore/Iridium#682]
Browser Name: Firefox
  Browser Version: 65.0, 64bit
  Operating System: Windows 8.1
  Software Type: Iridium Browser Add-on
  Software Version: 0.2.5
  Problem Description: Some videos don't load. They sit there with the white circle spinning. I can use the scrubber to see previews, but the video never loads or plays. Videos load normally with Iridium disabled. Clean profile with only Iridium installed shows same problem.
  Steps to reproduce: Attempt to watch any affected video. Here is one example: https://www.youtube.com/watch?v=GvcYHxP0bHY
  Additional details: Not all videos have the problem, but I cannot (at my level of tech prowess) figure out what is different about the ones that don't load.

**Comment by Corruptinglyneedful** [comment]
Known bug, you need to disable the "disable autoplay function"

**Comment by rachael7** [comment]
Thank you so much!

**Comment by pkmatador** [comment]
Is there a fix for it?

**Comment by rachael7** [comment]
Yes, as was mentioned in the thread, you have to enable the “Play Videos Automatically” setting in the Iridium add-on.  I also went into about:config and set media.autoplay.default to 1, and added the add-on Stop Autoplay Next for YouTube.  That’s got videos playing, without autoplay.
 
Rachael =7
 
Studio Seven, Greenfield
(413) 824-7443

**Comment by Corruptinglyneedful** [comment]
Don't actually disable auto play across Firefox with that about config command.  It messes up Twitch and auto thumbnail players when you hover over them.

**Comment by rachael7** [comment]
I don’t like stuff that autoplays, so that works for me; but to each their own.
 
Rachael =7
 
Studio Seven, Greenfield
(413) 824-7443

**Comment by Corruptinglyneedful** [comment]
Twitch wont' work at all though, with that preference set like that.  It refuses to load the player/stream.  Websites that show thumbnails to videos when you hover over them, will not move through properly.

I restored my Firefox and re-enabled this preference and it was causing the problem which I couldn't figure out because I'd set that about config option and forgotten.

You can do w/e you want but people need to know it doesn't just affect Youtube and certain sites will break with this preference enabled.

The only way to fix it without these down sides is to either use a new extension or script or wait for the author to fix it.

**Comment by rachael7** [comment]
Good to know, thank you. I never use Twitch, so I wasn't aware. I'll file that info away for when I run into something that uses the Twitch platform.

**Comment by pkmatador** [comment]
> Don't actually disable auto play across Firefox with that about config command. It messes up Twitch and auto thumbnail players when you hover over them.



> Known bug, you need to disable the "disable autoplay function"

Yeah that works, thnx! But it misses the point of having a autoplay function... I don`t really understand the code yet, so I`ll wait for a bugfix :)
