### ISSUE TITLE
@ParticleCore Can you change project licence to GPL or MIT? I'm sure people would like to contribute to it and create new features and bug fixes.

### ISSUE THREAD

**Issue by jiceja** [ParticleCore/Iridium#727]
@ParticleCore Can you change project licence to GPL or MIT? I'm sure people would like to contribute to it and create new features and bug fixes.

_Originally posted by @filips123 in https://github.com/ParticleCore/Iridium/issues/725#issuecomment-509339630_

This fork will accept pull requests: https://github.com/jiceja/Iridium

**Comment by Zegnat** [comment]
I actually came to ask about the licence too.

The actual LICENSE file ([as of today](https://github.com/ParticleCore/Iridium/blob/9211d7d0bb0d5304c7fc10a09293143e928e0791/LICENSE.md)) only seems to allow use of the source code “for learning and teaching purposes,” and not for creating new versions of the software. While the latest update to the repository was a change to the CONTRIBUTING file ([currently](https://github.com/ParticleCore/Iridium/blob/9211d7d0bb0d5304c7fc10a09293143e928e0791/CONTRIBUTING.md)) asking people to “please create _[their]_ own forks.” These two points seem to be at odds with each other.

It would be great if I could fork this repository and play around with it. But the way it is now, I would not recommend doing so without first obtaining permission from @ParticleCore per the licensing.

**Comment by bskyb-backport** [comment]
there are loads of fake forks of the old YouTube Plus script uploaded with different  names - license means nothing nowadays

**Comment by Zegnat** [comment]
> _[…]_ loads of fake forks of the old YouTube Plus script _[…]_

There used to be a [version of YouTube Plus available under MIT](https://github.com/ParticleCore/Particle/tree/f3e758ffd21086e4328ebc17f78d0e4b5c83e0c4), so who knows, maybe those are all fully legal 😉 

For the small set of features I want to use, I have instead decided to fork off of [YouTube High Definition](https://addons.mozilla.org/en-GB/firefox/addon/youtube-high-definition/). That one is available under [LGPL-3.0-only](https://spdx.org/licenses/LGPL-3.0-only.html). ([Source on GitHub](https://github.com/Zegnat/browserext-youtube-high-definition/tree/archive) for everyone’s convenience.) Would still love to be able to just fork Iridium without seeking prior approval though.

**Comment by ParticleCore** [comment]
> 
> 
> > _[…]_ loads of fake forks of the old YouTube Plus script _[…]_
> 
> There used to be a [version of YouTube Plus available under MIT](https://github.com/ParticleCore/Particle/tree/f3e758ffd21086e4328ebc17f78d0e4b5c83e0c4), so who knows, maybe those are all fully legal wink
> 
> For the small set of features I want to use, I have instead decided to fork off of [YouTube High Definition](https://addons.mozilla.org/en-GB/firefox/addon/youtube-high-definition/). That one is available under [LGPL-3.0-only](https://spdx.org/licenses/LGPL-3.0-only.html). ([Source on GitHub](https://github.com/Zegnat/browserext-youtube-high-definition/tree/archive) for everyone’s convenience.) Would still love to be able to just fork Iridium without seeking prior approval though.

I'm ok with you forking the project as long as you don't monetize it by means of ads and other nagware, donations and every other passive monetization done outside the project is alright with me. Great projects by the way!

**Comment by andrewjmetzger** [comment]
@ParticleCore Thanks for allowing forks! Could you please change the repository license to something more permissive to make it official, though?

The two "big names" in the license scene right now are [GPL v3](https://choosealicense.com/licenses/gpl-3.0/) and [MIT](https://choosealicense.com/licenses/mit/)

I've linked to human-friendly summaries of each from GitHub's own [Choose a License](https://choosealicense.com/) project, but the super-quick TL;DR is: Both MIT and GPL let people do pretty much anything, but the GPL requires that any code be open-sourced.

Neither would prevent people from doing nasty things like creating a clone to inject ads/nagware/etc., but, as I see it:

1. Iridium's current license prevents any and all open-source contribution, which is decidedly not good for the project's long-term health. (Iridium even began as a fork of YouTube Plus -- what happens when you aren't contributing anymore?)
1. The vast majority of open-source contributors submit Pull Requests in good faith, and want to keep the project alive and healthy. (Personally, I'm a huge fan, so I'm counting myself here, too.)
1. You as the repository owner (or a trusted ally, if you choose to appoint any) have to review every PR before it gets merged, so you can still reject it, if necessary
1. Some people are just evil, and a license isn't going to stop them from screwing with knock-offs anyway
1. Making it clear that `particlecore/iridium` is *the real* Iridium should keep potential knock-offs from gaining too much traction. Want some inspiration? Take a look at [uBlock Origin v. uBlock dot org](https://github.com/gorhill/uBlock/wiki/uBlock-Origin-is-completely-unrelated-to-the-web-site-ublock.org) for an example of how to do this the right way.

Both the MIT license and the  GPL are great, and they are fairly similar; however, If you are incredibly concerned about the future of Iridium, I would suggest using the GPL. Otherwise, the MIT license is fine (in fact, I use it for most of my projects). Then again, as noted above, bad actors are probably going to ignore the license anyway.

I'm eager to hear your thoughts on this; let's discuss. 😃

**Comment by wadawada** [comment]
@ParticleCore Can you actually let others fix bugs?

**Comment by ParticleCore** [comment]
Copying from a previous discussion in https://github.com/ParticleCore/Iridium/issues/419#issuecomment-379087578

---

> Its unfortunate that you do not use GPL for your source code as project would grow faster and be developed much faster better and more stable.

I understand the argument, but it is not applicable here due to a few blockades:
 - Mozilla has a very strict policy for all add-ons submitted to their store, which means any "bad" code that slips through will become a problem
 - I would have to inspect every single submission to ensure that there would be no "bad" code (something as simple as an `innerHTML` assigned to a variable that only contains static text), in a sense I would have to be a Mozilla reviewer
- I would have to teach contributors how the extension is structured and all the logic that only I know, because most just don't bother reading anything these days
 - I would have to explain over and over again every time another user would try to make a pull request for a video/audio download feature why it can't be implemented since Chrome store would ban the extension
- I already hardly have time to fix bugs and develop more features, let alone make sure the code contributions are safe and with the correct structure
