### ISSUE TITLE
All features have been deleted??

### ISSUE THREAD

**Issue by BitGrub** [ParticleCore/Iridium#745]
The brand new settings menu looks nice, but why delete all the features? Like, literally, they're all gone except for "force max resolution thumbnails" and "play videos automatically" (a native firefox feature now).

What gives?

**Comment by BobbyWibowo** [comment]
It's still being rewritten from scratch. 1.0.0 is pretty much a sneak peek of what's already written. Most, if not all, of the old features will eventually come along one by one.
Just take it as to get more debugging feedbacks and whatnots.

**Comment by JackDinn** [comment]
just been forced (well auto-updated) to this version. Even though the thumbnail hover player had not worked for ages i did still use some of the other features, now there are none. I have no use for this addon any more since i don't know how to downgrade it back to what it was so unfortunately I've disabled it.

**Comment by ParticleCore** [comment]
This has been explained here: https://github.com/ParticleCore/Iridium/tree/1.0.0
If users want to use the previous version you can find them here https://github.com/ParticleCore/Iridium/commits/master/dist/Iridium.xpi

Remember to disable auto-update until you wish to update.
