### ISSUE TITLE
Settings bug

### ISSUE THREAD

**Issue by Maltbrew** [ParticleCore/Iridium#748]
Why can't I change my settings anymore?

**Comment by 84436** [comment]
Apparently the whole extension is being reworked, since the included settings page (manually unzip the extension, then open html/options.html) is very bare and only has 3 toggles: "Dark theme", "Play videos automatically" and "Force max thumbnail resolution", with the rest of the tabs having only the word "Coming soon." I have yet to find a way to get into the settings page from within Firefox.

I guess we might have to wait (or roll back to the old version for the time being.)

**Comment by Acid-Crash** [comment]
>> I have yet to find a way to get into the settings page from within Firefox.
This can be achieved by adding extension's button to the toolbar

**Comment by BitGrub** [comment]
Just want to thank the dev for all his work so far! Hope the rework goes smoothly.


Also, I'd like to say hope that leaving at least one of these issues up would prevent others from making the same one over and over again, but I know it won't lmao.
You should at least update the main page (https://github.com/ParticleCore/Iridium) so people can find out what's happening on their own

**Comment by 17721** [comment]
My theme is screwed (search bar is black and the rest is white). The settings icon is gone. Theater mode isnt working anymore

**Comment by BitGrub** [comment]
> My theme is screwed (search bar is black and the rest is white). The settings icon is gone. Theater mode isnt working anymore

How did this moron get so far in life without the ability to read?
