### ISSUE TITLE
Video download button

### ISSUE THREAD

**Issue by erkinalp** [ParticleCore/Iridium#755]
Can you add a "download video" button(always present on CC licensed videos and opt-in with standard ones) when not logged in as a premium user? Iridium conflicts with other extensions adding such buttons.

**Comment by ParticleCore** [comment]
I asked to explain better what you were trying to say, I still don't get it. licensed videos and opt-in with standard ones? When not logged in as a premium user? What does that mean?

**Comment by erkinalp** [comment]
When logged-in as non-premium: Premium users already see that button on all videos.
Always-on with CC-licensed videos: Videos licensed under CC-BY can legally be downloaded but no button appears by default.
Opt-in with standard videos: Same reasoning as above, but the user can choose to risk or avert the risk (against TOS).
Not available with premium videos when logged in as non-premium: Same as above.

**Comment by ParticleCore** [comment]
Now I understand that you mean YouTube Premium, took me longer to understand than I'd like to admit.
I'm afraid that I cannot do that because I don't have a Premium account to test with nor do I wish to pay for multiple reasons.
I'll try to make the feature as less conflicting as possible but I cannot promise anything.
