### ISSUE TITLE
You don't do releases like that, especially 1.0

### ISSUE THREAD

**Issue by burjui** [ParticleCore/Iridium#757]
First, it's common knowledge that a 1.0 version of something is supposed to at least work well or possibly even be feature-complete, whatever that means for a particular piece of software. Right now, it's the complete opposite, since almost every feature is either missing or broken.

Second, even if your idea about what constitutes a 1.0 version differ from the common one, you should not force everyone to update to a non-working version and then somehow discover that this is planned.

Third, **thanks a lot** for dark theme by default. I spent at least an hour mucking around with cookies, caches and googling rare Youtube bugs only to discover that it's an feature of Iridium. And I had to spend that much time because the only feature that you didn't break is disabled autoplay, so I didn't even notice that Iridium updated, because it's kinda hard to notice the missing Iridium icons under a video when I'm trying to understand how the hell Youtube is still dark after I switched the night mode on and off, reloaded the page, restarted the browser, removed cookies, repeated all that 10 times...

Don't get me wrong, I love Iridium. But what you did there is just madness. And it's not some sacred hardcore developer knowledge that you should not do that, just common sense. In all honesty, it looks as if somebody hacked your github account and pranked us. I get it, Iridium is free and all that, you have no obligations, etc. But Iridium has users, and it's not nice to do what you did.

So anyway, I had to install version 0.25, and right now Iridium is the only extension I have with auto updates disabled. At least it works. Right now, the best option for you is to issue an update that would revert the changes back to 0.25. Then, when you're finished "refactoring", you can release the new _working_ version. You know, you don't have to publish an unfinished work, so don't do it until it's finished.

**Comment by ParticleCore** [comment]
There were over 400 users complaining that the majority of the extension was not working at all. There's no way for me to ask each and every user what is still working or test it on my end given the myriad of experiments that YouTube tests on each user everyday, it can reach to over 100 for a single user.
That tied along with users that force old layouts of YouTube and other extensions to compensate for the lack of working features, I have no way of knowing nor do I have any free time to be working on a proper way to update the extension after eight months of not being able to do anything at all.
I already apologized for the abrupt change on the release, complaining even more after that won't change anything, in fact it would be completely meaningless releasing the extension with all the features developed - which might take months to do - or releasing with every new feature that is implemented, it would also be completely meaningless to do any side beta or just a plain release because there will always be users that will complaint about change regardless.

And I know that because that's exactly what happened when the previous extension undergone massive changes through a beta channel and was only released to stable once fully featured rich; most uses still complained about it.

So in the end - for me - it makes no difference to release it in a different way or wait until everything is done, at least this way users will not have to wait for the extension to be fully done before being able to use it.

I think I already mentioned this before, but I couldn't care less if the users are upset about anything, I apologize out of respect, but there will always be upset users for multiple reasons, some reasons even that are completely ludicrous and unfair, so I've got tired of it a while ago.

Case in point, to your "Thanks a lot": the changes were documented. Is it my fault as well that you didn't remember to check for extension changes in recent updates?

I most certainly will not issue any update that rolls back anything. You did well to go back to a previous version and disable auto-update because this is how it will be for quite some time until most of the features have been implemented.
