### ISSUE TITLE
YouTube embeded videos show black box

### ISSUE THREAD

**Issue by cca310** [ParticleCore/Iridium#782]
https://www.reddit.com/r/firefox/comments/dklz0g/embedded_youtube_videos_only_show_a_black/f4i3p1o/

https://i.imgur.com/r734O3m.png

Issue goes away when I uninstall iridium and clear firefox cache

firefox 70.0 64 bit windows 10
Iridium 1.2.3

**Comment by BitGrub** [comment]
Same here

**Comment by ParticleCore** [comment]
This shouldn't be happening, I was certain I had excluded anything that wasn't on YouTube's main domain, thus excluding iframes.

Will see that it gets fixed as soon as possible.

**Comment by ParticleCore** [comment]
Wait a second, this is not happening to me. What exactly are the steps to recreate the problem?

Remember to follow the troubleshooting steps as requested: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug#troubleshooting

**Comment by cca310** [comment]
> 
> 
> Wait a second, this is not happening to me. What exactly are the steps to recreate the problem?
> 
> Remember to follow the troubleshooting steps as requested: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug#troubleshooting

the easiest way for me to get it to happen is to go to https://sync-video.com/.
click create new room
press join
enter youtube video link and press the "+"

I just installed iridium again to test my steps. it may not happen the first time you try these steps ^. it took me 4 times of going to sync video for it to happen: https://i.imgur.com/tjNMhM3.png

also, refreshing this page a few times causes it to be black: https://www.reddit.com/r/videos/comments/dj7mp1/paul_rudd_does_a_historic_dab_while_on_hot_ones/

**Comment by ParticleCore** [comment]
@cca310 It's not happening for me. Can you tell me which settings you have enabled and disabled in the extension?

**Comment by cca310** [comment]
> 
> 
> @cca310 It's not happening for me. Can you tell me which settings you have enabled and disabled in the extension?

I have everything enable except for quick controls and sync settings

Dark theme: **enabled**
Quick controls: **disabled**
Play videos automatically: **enabled**
Force max thumbnail resolution: **enabled**
Allow HFR streams (60fps): **enabled**
Sync Settings: **disabled**
Show settings button in YouTube: **enabled**


also, you say it's not happening for you. I have the same thing for my laptop. I can't get the black box to happen on my laptop. only my desktop.

**Comment by ParticleCore** [comment]
@cca310 Much appreciated. I've been with your settings scrolling non-stop on this page which contains plenty of videos like those and not once has failed to load yet: https://www.reddit.com/r/videos/

If you're not having this problem on your other computer then it's probably a YouTube bug like in #771 in which case clearing your website cache and/or cookies for YouTube on the computer with this problem should be enough to make it go away.

**Comment by LunarBear** [comment]
Iridum literally broke YouTube for me. Not only did I have black boxes for every YouTube embedded video for the last few days (and couldn't figure out what was wrong), but when I **disable** the extension it just totally breaks YouTube for me (the site doesn't show anything anymore apart from the title). It was highly annoying because I tried to diagnose what the hell was wrong with YT embed videos by going into Private Mode and/or disabling a bunch of addons including Iridium, but thought it was not Iridium considering when I disabled it everything was still broken.

I'm sorry, I've been a long time user, was okay with the lack of update and broken features for months and tried to be understanding, but Iridium in its current state is a disgrace. 
An extension should never break things MORE when you disable it. As a simple user that's just crazy to me.
It should NOT be a recommended Firefox addon in its state and I reported it (not out of spite at all, but to prevent other people having to try to figure out for days what's wrong with their YouTube like me), explained the issues I had with it and how it pretty much completely broke YT for me on all my devices for several days.

It was a great extension but very poorly managed. As many others said I still don't understand why the dev decided to completely scratch it and push the new version with almost no feature and which introduced bugs, instead of letting the stable old version stay (even with its broken features) while he worked on the new version in the same time and pushed it when it was out of pre-alpha, stable and with a bunch of actual features.

Time to move on for me.

**Comment by ParticleCore** [comment]
@LunarBear The extension does not break YouTube after it is disabled or uninstalled, that's a YouTube bug that happens to be surfaced after using the extension: https://github.com/ParticleCore/Iridium/issues/771

Also maybe you should take a minute to read before writing what you did: https://github.com/ParticleCore/Iridium/issues/737#issuecomment-541321036

Report whatever you want to report, the situation has already been explained and detailed before. 

Good luck on your moving on, next time don't hijack an issue to express your feelings.

**Comment by cca310** [comment]
@ParticleCore Does this mean anything. I'm not a developer or anything. I'm just trying to research the issue https://www.reddit.com/r/firefox/comments/dht48d/youtube_embeds_completely_broken_black/f3ymh0h/?context=3


Another quick question. If it's a YouTube bug, why do I only experience it with Iridium installed. This isn't meant to be a snarky question. I just genuinely don't know.

**Comment by ParticleCore** [comment]
@cca310 That was actually really helpful, it's tracking down exactly to a portion of the code that might be a result of what the extension should be modifying.

![ss2](https://user-images.githubusercontent.com/9222661/67334715-232ed900-f512-11e9-8d57-a58f51436329.png)


This is making me think that the extension is not acting up at all, it's doing exactly what it is told to do, however there might be a bug in Firefox related to the new method that is being implemented for the feature implementation and it is causing the **cached** file to be saved with the modification, which should not be happening at all.

In this case what might be happening is the `base.js` and any other cacheable files the extension modifies are being saved with modifications done to the code.

This is not so much a problem while the extension is running **inside** the YouTube website because the code that is trying to run is finding the expected functions, but once those same files are being loaded outside the domain - say embedded on another website - then it will fail fast.

This is a big problem and shouldn't be happening, Firefox is storing the file modifications that should be only live in the browser memory, not in a cached file.

I will implement immediately measures to prevent this from having this kind of catastrophic failure and fallback to the original code if the extension functions are not found.

If you don't mind I will need your help to confirm if the fix worked after I'm finished.

**Comment by ParticleCore** [comment]
@cca310 Can you install the version 1.2.4 I just committed? Remember to uninstall the one you have installed and if you don't know how to install it from GitHub follow the instructions: https://github.com/ParticleCore/Iridium/wiki/Download#how-to-install-add-on-from-github

Let me know if the fix worked and hopefully this really terrible situation is finally solved by this workaround.

**Comment by cca310** [comment]
@ParticleCore I repeated my steps 20 times and the black box never happened. It seems to be fixed.

thank you for fixing this!

**Comment by ParticleCore** [comment]
Not at all, thank you for looking that further in to the issue, that file you linked was what helped understand what was going on. I'll go ahead and push this to everyone else since there's a lot of users affected by it.

**Comment by BubiBalboa** [comment]
Can you please file a bug report so Mozilla can fix this?

**Comment by ParticleCore** [comment]
@BubiBalboa It's a side effect of a bug that was already reported over 8 months ago and hasn't been fixed yet: https://bugzilla.mozilla.org/show_bug.cgi?id=1530408

It's loading the cached file incorrectly and allowing it to be modified by the `filterResponseData` api or similar side effect to my understanding.

**Comment by def00111** [comment]
It looks like this bug will be fixed in Firefox 76.
