### ISSUE TITLE
An error occurred. Please try again later.

### ISSUE THREAD

**Issue by megamorphg** [ParticleCore/Iridium#858]
Everytime I open a new video, I get an error "An error occurred. Please try again later."

The only way around this I found was to disable "Play Videos Automatically."

![image](https://user-images.githubusercontent.com/1782353/87686737-b4e21480-c739-11ea-85a4-40ff71c8acaf.png)

**Comment by RayKoopa** [comment]
Same issue here, since months, made me uninstall the extension.

**Comment by HyphenSam** [comment]
Same issue. Your workaround doesn't work for me, as it makes all YouTube videos not load instead of giving an error.

**Comment by Ruratae** [comment]
Same here. Disabling autoplay makes it so I need to reload several times instead of once. 
I tried disabling all other settings and allowing ads, this didn't do much. I disabled uBlock Origin to make sure ads got through and the video seems to work perfectly fine with ads, but only when autoplay is disabled. When autoplay is enabled, I have only gotten either no video loading at all (I can't even see player controls or a buffer wheel) or the same kind of error message.
This seems to be related to ad blocking and the autoplay feature in conjunction, as the issue doesn't occur when only uBlock Origin is enabled.

**Comment by ekaunt** [comment]
try adding 
```js
                        // reload the page if the "An error occurred. Please try again later." message shows up
                        if (document.getElementsByClassName("ytp-error").length) { window.location.reload() }
```

right after (what at around line number 3171)

```js
                    loadStart: function (event) {
```

in the userscript version of iridium

**Comment by ParticleCore** [comment]
Issue might no longer be relevant in the upcoming version, closing outdated cases for maintenance purposes.
