### ISSUE TITLE
As of today, Iridium  prevents YT videos from loading

### ISSUE THREAD

**Issue by octapusxft** [ParticleCore/Iridium#873]
On YT when I tried to watch a video the player would not load and show a blank backround

{
    "manifest_version": 2,
    "name": "Iridium for YouTube",
    "version": "1.2.7",
    "description": "YouTube with more freedom",
    "default_locale": "en_US",
    "options_ui": {
        "page": "html/options.html",
        "open_in_tab": true
    },
    "icons": {
        "16": "icons/16.png",
        "32": "icons/32.png",
        "48": "icons/48.png",
        "64": "icons/64.png",
        "128": "icons/128.png"
    },
    "browser_action": {
        "default_icon": {
            "16": "icons/16.png",
            "32": "icons/32.png",
            "48": "icons/48.png",
            "64": "icons/64.png",
            "128": "icons/128.png"
        }
    },
    "background": {
        "page": "html/background.html",
        "persistent": true
    },
    "content_scripts": [
        {
            "matches": [
                "*://www.youtube.com/*"
            ],
            "js": [
                "js/content-script.js"
            ],
            "run_at": "document_start"
        }
    ],
    "permissions": [
        "storage",
        "privacy",
        "cookies",
        "webRequest",
        "webRequestBlocking",
        "*://.youtube.com/*",
        "*://www.youtube.com/*"
    ],
    "applications": {
        "gecko": {
            "id": "unlisted-iridium@particlecore.github.io",
            "strict_min_version": "57.0",
            "update_url": "https://github.com/ParticleCore/Iridium/raw/master/bin/update.json"
        }
    }
}

**Comment by mike10dude** [comment]
same thing is happenning to me

**Comment by Ja-Peter** [comment]
Same here, too. It started today.

**Comment by edjacob25** [comment]
Same here, both AMO and Github versions, Fiirefox 86 on Windows

**Comment by d4k0** [comment]
I also noticed this today using Firefox 86. It seems that this project is dead.

I switched to "Enhancer for YouTube" (the last update was in March 2020, but it still works). Furthermore, I found ["Improve YouTube!"](https://github.com/code4charity/YouTube-Extension) which is open source. There is no official Firefox version yet (it has to be installed as temporary add-on in Firefox), but it seems that there will be one soon.

**Comment by NekoAlosama** [comment]
@ParticleCore

**Comment by Eisys** [comment]
I still use "old" Iridium, latest version(0.2.5) before it got nuked and remade and then abandoned..
Works fine, with a few minor edits.

I NEED Iridium's miniplayer, no other addon has one nearly as good. 
I NEED Iridium's "player shortcuts always active" feature, no other addon has that, period.. Which seems idiotic, I don't want some custom shortcuts or custom UI to control audio or whatnot, just let the default shortcuts be active all the time..
And Iridium's handling of hiding endscreen cards is also the best.

Otherwise I'd be using Enchancer or Improve as well.

**Comment by ParticleCore** [comment]
Sorry, everyone, but it has been impossible for me to dedicate some of my time to this project, but I have never abandoned it. I apologize for its current state, I know it is not working - or barely working with old versions, but I cannot give any time frame on when I'll be able to focus again on it. One thing is certain, I have not abandoned it, otherwise I would have made an official announcement.

**Comment by stepikovo** [comment]
Any updates on this issue, making the plugin literally unusable?

**Comment by ParticleCore** [comment]
Redundant questions do not provide a good contribution to this issue. Locking to prevent more spam.

**Comment by ParticleCore** [comment]
Working on a new version, so any opened issues might no longer be relevant.
