### ISSUE TITLE
'Player always visible' feature on original 0.2.5 version of Iridium

### ISSUE THREAD

**Issue by Eisys** [ParticleCore/Iridium#883]
Hi.

I've been using 0.2.5 of the original Iridium script for years now. 

For a while it was for many of its options but one-by-one most things stopped working.

BUT, the one thing, the most important feature has been working just fine. "Video stays always visible while scrolling"
Iridium's version of this feature is unmatched. So simple, worked perfectly.

Keyword being 'worked'. Until today. Youtube updated something again. This amazing feature finally broke.

Now I know you don't seem to work on Iridium anymore, atleast publicly, and even less the original version.
But, if you have any sort of free time and are willing, please, could you look at your code to see if maybe there is an easy fix for it. I have a custom CSS style for Youtube and the custom player width that I had set up, also broke; they changed the element name of the player. I added the new name and the style works again. So I'm hoping there could perhaps be a similarly easy fix for the code in the Iridium 0.2.5 script.

I know just enough about CSS and Inspect Element helps a ton but I know absolutely nothing about actual coding or scripting so fixing it myself is not something I can do.

What would be even more awesome was if you made just the "Player always visible" feature as an entirely separate script but that's probably too big of a project.

So, if you can help, I'd appreciate it A LOT but if not, thanks for reading and thanks for many years of making Youtube better.

**Comment by ParticleCore** [comment]
I'll be redesigning the entire extension and reworking all of its features (some might no longer make sense to keep, but it will be on a per case basis). This one is a feature I do enjoy so I will be definitely adding it in the future, but not right now.

I'm going to focus on one, or a couple of features first, and then work on more over time.

However, since it will be an entire redesign, it does not make sense to me to keep any issues open at the moment so I will be closing all issues that are open so any new ones will be related to the upcoming version.
