### ISSUE TITLE
Playback speed setting incorrectly enforced

### ISSUE THREAD

**Issue by Bertaz** [ParticleCore/Iridium#921]
Whatever `defaultSpeed` is set to is getting enforced even after manual change by the user.
This happens everytime the video is paused, played, skipped forward or skipped backward. Either by key or by mouse click.
This doesn't happen with similar setting `defaultQuality` (Video quality)

Repro:
1. Check Iridium Playback speed setting (default Normal=1x)
2. Go to youtube video, select a different speed (e.g. 2x)
3. Video starts playing with selected speed
4. Pause and start the video/skip forward
5. Video reset with speed in settings

Expected outcome:
Video starts with the selected speed, but, after a manual change by the user, keeps the user selected speed without enforcing the settings one.

Iridium 2.0.2 | Firefox 122.0 | Win 10

**Comment by ParticleCore** [comment]
Just to confirm that I understand what you are trying to explain:

There should be a default (auto) option in that feature so it would not enforce the setting on its own when no other value is selected?

The default quality does have that Auto option, meaning the extension leaves the player do whatever it wants, but for speed there is no such option.

Perhaps that is what is missing from the speed option, can you confirm I understood you correctly?

**Comment by Bertaz** [comment]
> There should be a default (auto) option in that feature so it would not enforce the setting on its own when no other value is selected?

No I meant it should work like default quality works right now. If I select something different from `auto` (e.g. `720p`) and I open a video, the video start at 720p. While watching if I select `240p` on the youtube video the video starts playing with 240p quality, if I then pause the video, the video keeps the 240p quality I chose, instead of switching back to 720p from Iridium settings.

The issue is that what you set in playback speed is continously enforced, instead of only at the start when you open a video.

**Comment by ParticleCore** [comment]
That'll be tricky. Both features use the same logic with a small distinction, the quality can tell whether the user changed the quality or not because the player will return "auto" for preferred quality:

https://github.com/ParticleCore/Iridium/blob/d3fe64f010d702f7cd8ffea4d9d163d3ef35a072/src/js/background-inject.js#L92-L93

Other than that it enforces it in the same way as the speed option.

The reason it is enforced on playback changes is because the video can start via a number of different ways, and it is not reasonable to track them all nor is it guaranteed to work reliably.

To only apply it for the first time is currently not something that I was able to find how to do it in a reliable way, and even if I were to implement some sort of tracking logic, it will be prone to scenarios where it will fail, such as when the user navigates back and forth.

Unfortunately there are no events that tell when the video starts playing for the first time and applying the speed change persists, quite often this is ignored while the video is buffering for the first time, as an example.

I will however implement an Auto option which will let the player do its own thing at the very least, but I cannot promise I will be able to achieve what you asked. It is not that it is impossible, but at first glance will require quite some logic that is not guaranteed to work, and might be fragile so it could stop working easily with another YT update/changes.

**Comment by Bertaz** [comment]
> I will however implement an Auto option which will let the player do its own thing at the very least, but I cannot promise I will be able to achieve what you asked. It is not that it is impossible, but at first glance will require quite some logic that is not guaranteed to always work, and might be fragile so it could stop working easily with another YT update/changes.

That would be perfect considering those technical difficulties.
I suggest making `auto` the default option. Right now extension's users may be confused by the video not keeping their manual selection after playback changes

**Comment by ParticleCore** [comment]
Good news, I might have found a way to also improve the behavior as you suggested. However, it would always enforce it whenever a new video starts playing, but will no longer enforce it during the playback of that video. If the video changes, it will enforce it once again.

Auto will definitely be the default option for sure, don't know why I didn't even think of it at the time.

**Comment by ParticleCore** [comment]
Hopefully the workaround is a solid implementation, at the very least it was simple to implement which made it worthwhile. If it ends up facing odd scenarios where it does not work correctly I will revisit this.
