### ISSUE TITLE
Re-implement the Always Visible player

### ISSUE THREAD

**Issue by JoshS-dev** [ParticleCore/Iridium#941]
It would be nice to re-introduce the player that continues showing the youtube video in the bottom-right of the screen as you scroll down into the comments. It used to be part of Iridium.

**Comment by ParticleCore** [comment]
The feature is progressing well:


https://github.com/ParticleCore/Iridium/assets/9222661/fb348d9c-f2f3-4cde-a212-e12f8d74d148

However, the feature implementation has become more complex than the previous implementation largely due to the significant changes the new YT has compared to before.

Because of this I will probably not make it customizable since it would make it unacceptably complex. If I find a way to make it less complex I might consider revising this.

**Comment by ParticleCore** [comment]
Finalizing the feature implementation and testing some odd scenarios. Wondering if the feature description will be sufficiently clear to explain what it does, and how it can be moved
![image](https://github.com/ParticleCore/Iridium/assets/9222661/1f43c5bb-d7db-4a7e-87ba-7d0028733e8f)

**Comment by JoshS-dev** [comment]
In my personal opinion its a little wordy, I would go with "The player will become a mini player in the bottom-right corner [once the player is no longer in focus/if it is scrolled past/when it is not on the screen/if one scrolls down to the comments]"

Though honestly, yours is still workable.

**Comment by ParticleCore** [comment]
Thanks for the suggestion, it inspired me to improve it into this one. I think it is much better now.

![image](https://github.com/ParticleCore/Iridium/assets/9222661/10fe4044-8211-4f5e-817c-30c453b9452e)
