### ISSUE TITLE
Clips not working when Iridium is enabled

### ISSUE THREAD

**Issue by eduzappa18** [ParticleCore/Iridium#954]
Youtube clips are not working with Iridium enabled
The video player is all black and the description is not showing correctly
they work normally when Iridium is disabled

tested on firefox 123.0 with Iridium 2.0.6

![image](https://github.com/ParticleCore/Iridium/assets/11097763/88901095-e767-4ab6-bcff-942191c9073a)

**Comment by ParticleCore** [comment]
As a temporary workaround for now I believe enabling autoplay will make the clip work again, can you confirm that works for you?

**Comment by ParticleCore** [comment]
Seems like the issue is worse than I thought. If I cannot find a reliable way to enforce autoplay control on clip pages I might have to not enforce it only in those pages for the time being.

However, I believe modern browsers have the ability to refuse automatic video playback to a certain degree, I will explore this next to see if I can make it work. This would be a perfect solution because it would mean the extension would no longer need some aggressive overrides.

**Comment by ParticleCore** [comment]
Found the issue. When the video is initialized, or loaded with new data related to a video clip the process it undergoes is different than a normal load. As a result the automatic ability for the video to stop itself does not exist, so when it tries to stop internally when autoplay is disabled it hits an error:

![image](https://github.com/ParticleCore/Iridium/assets/9222661/7909626d-2bd0-4ec3-aadb-841b32501e61)

The new workaround I'm testing is a form of play control instead of redirecting internal API methods, and so far appears to be working well with clip videos and autoplay off. However, without the stopVideo method the videos will buffer while paused but since clip videos so far do not appear to be stoppable it won't make a difference for that case specifically.
