### ISSUE TITLE
Option for full dates to appear by default

### ISSUE THREAD

**Issue by JoshS-dev** [ParticleCore/Iridium#974]
![image](https://github.com/ParticleCore/Iridium/assets/34352316/28a4761f-4572-4bfc-8221-52eb18dd4c8e)

I think there should be an option to replace the default youtube "2 years ago" "14 hours ago" such that the full date, as shown in the screencap, is always visible. Perhaps with options for different date standards, and perhaps a setting for letting the '14 hours ago' be and only changing when dates get to over a week, for example.

**Comment by ParticleCore** [comment]
I had that option in the past, but back then it was way easier to do something like this, whereas now it is so much complicated and I don't see that much of an advantage given that it is available with the hover title.

As for the recommended videos, the information is not available in the current page, meaning a separate request would need to be made for every single video in that list, and since it is async the information would still show the relative time before it would show the specific time.

One thing to note; the full uploaded time and and view count has been showing every now and then by default on YouTube, meaning it is an experiment option that might be turned off or on so you might actually see it happening for you at random.

![image](https://github.com/ParticleCore/Iridium/assets/9222661/4bace389-91bc-4bb3-b697-3a423d68fe9a)


However, I wouldn't rely on experiments for feature implementation since they can easily be removed at any time (something often experienced in the past with YouTube Center extension too), which is quite common, especially since they have been actively pushing for animated view count and time as well:

![image](https://github.com/ParticleCore/Iridium/assets/9222661/61fe805e-cc71-4ffb-992c-6cfed255c863)

![image](https://github.com/ParticleCore/Iridium/assets/9222661/2aa3ec01-c60b-46f7-92ee-b9ef84111bca)


![1](https://github.com/ParticleCore/Iridium/assets/9222661/b9f86e77-521a-4679-a91e-f2d0182a154f)
