### ISSUE TITLE
Settings for hiding page sections

### ISSUE THREAD

**Issue by hl2guide** [ParticleCore/Iridium#990]
Please allow us to hide/show the:

- video description
- comments section
- right sidebar recommended videos

_Unless I've missed an existing feature in the settings page._

**Comment by ParticleCore** [comment]
These would be far better off as cosmetic styles (for example, using Stylish extension).

I did have something like this in the past for the comment section, but it kept becoming unstable due to the frequent source code changes, and eventually gave up since it wasn't something I used enough to justify maintaining it. I do not feel any different about it now either, so I will not do it for now.
